"""Amazon Bedrock inference, Guardrails, and the vector stores behind a Knowledge Base.

Docs: https://vedicreader.github.io/awseasy/ai.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ai.ipynb.

# %% auto #0
__all__ = ['DEFAULT_MODEL', 'EMBED_MODEL', 'CONTENT_FILTERS', 'PII_ENTITIES', 'inference_profile', 'list_bedrock_models',
           'converse', 'create_guardrail', 'guardrail_ref', 'bedrock_policy', 'create_aoss_collection', 'aoss_endpoint',
           'create_kb', 'kb_data_source', 'sync_kb', 'create_opensearch', 'opensearch_endpoint',
           'opensearch_admin_creds']

# %% ../nbs/01_ai.ipynb #2369fef3
import json, secrets, string
from .core import named, poll_until, tag_list
from .network import create_secret, get_secret

# %% ../nbs/01_ai.ipynb #92453207
DEFAULT_MODEL = 'anthropic.claude-3-5-sonnet-20241022-v2:0'
EMBED_MODEL = 'amazon.titan-embed-text-v2:0'

def inference_profile(model_id, prefix='us') -> str:
    'Cross-region inference profile id, e.g. "us.anthropic.claude-...". Newer models require one.'
    return model_id if model_id.startswith(f'{prefix}.') else f'{prefix}.{model_id}'

def list_bedrock_models(auth, provider=None) -> list:
    'Foundation models available on demand in this region, optionally filtered by provider.'
    kw = {'byInferenceType': 'ON_DEMAND'}
    if provider: kw['byProvider'] = provider
    return auth.client('bedrock').list_foundation_models(**kw)['modelSummaries']

def converse(auth, prompt, model_id=DEFAULT_MODEL, system=None, max_tokens=1024,
             temperature=None, guardrail=None, region=None, **_) -> str:
    'Call any Bedrock foundation model and return its text. guardrail=(id, version) enforces a guardrail.'
    kw = dict(modelId=model_id,
              messages=[{'role': 'user', 'content': [{'text': prompt}]}],
              inferenceConfig={'maxTokens': max_tokens})
    if temperature is not None: kw['inferenceConfig']['temperature'] = temperature
    if system: kw['system'] = [{'text': system}]
    if guardrail:
        gid, gver = guardrail if isinstance(guardrail, (tuple, list)) else (guardrail, 'DRAFT')
        kw['guardrailConfig'] = {'guardrailIdentifier': gid, 'guardrailVersion': str(gver)}
    r = auth.client('bedrock-runtime', region=region).converse(**kw)
    return ''.join(b.get('text', '') for b in r['output']['message']['content'])

# %% ../nbs/01_ai.ipynb #c58141d4
CONTENT_FILTERS = ['HATE', 'INSULTS', 'SEXUAL', 'VIOLENCE', 'MISCONDUCT']
PII_ENTITIES = ['EMAIL', 'PHONE', 'NAME', 'ADDRESS', 'US_SOCIAL_SECURITY_NUMBER',
                'CREDIT_DEBIT_CARD_NUMBER', 'PASSWORD', 'AWS_ACCESS_KEY', 'AWS_SECRET_KEY']

def _content_policy(strength):
    # PROMPT_ATTACK is input-only: an output strength other than NONE is rejected by the API.
    f = [{'type': t, 'inputStrength': strength, 'outputStrength': strength} for t in CONTENT_FILTERS]
    return {'filtersConfig': f + [{'type': 'PROMPT_ATTACK', 'inputStrength': strength,
                                   'outputStrength': 'NONE'}]}

def create_guardrail(auth, name, strength='HIGH', pii=None, pii_action='ANONYMIZE',
                     denied_topics=None, blocked_words=None, kms_key_arn=None,
                     blocked_message='This request cannot be answered.', tags=None,
                     **compliance_opts) -> dict:
    'Create a Bedrock guardrail with strict content filters and PII redaction. Idempotent by name.'
    c = auth.client('bedrock')
    kw = dict(name=name,
              description=f'awseasy guardrail for {name}',
              contentPolicyConfig=_content_policy(strength),
              sensitiveInformationPolicyConfig={'piiEntitiesConfig': [
                  {'type': t, 'action': pii_action} for t in (pii if pii is not None else PII_ENTITIES)]},
              blockedInputMessaging=blocked_message,
              blockedOutputsMessaging=blocked_message,
              tags=tag_list(tags, 'key', 'value'))
    if denied_topics:
        kw['topicPolicyConfig'] = {'topicsConfig': [
            {'name': t['name'], 'definition': t['definition'], 'type': 'DENY',
             'examples': t.get('examples', [])} for t in denied_topics]}
    if blocked_words:
        kw['wordPolicyConfig'] = {'wordsConfig': [{'text': w} for w in blocked_words]}
    if kms_key_arn: kw['kmsKeyId'] = kms_key_arn
    try: return c.create_guardrail(**kw)
    except c.exceptions.ConflictException:
        return next(g for g in c.list_guardrails()['guardrails'] if g['name'] == name)

def guardrail_ref(guardrail) -> tuple:
    'Turn a create_guardrail response into the (id, version) pair converse() expects.'
    return guardrail['guardrailId'], guardrail.get('version', 'DRAFT')

# %% ../nbs/01_ai.ipynb #4e80c1a1
def bedrock_policy(auth, models=None, bucket=None, kms_key_arn=None, collection_arn=None) -> dict:
    'Least-privilege policy: invoke only the named models, read only the named bucket and key.'
    p = auth.partition
    model_arns = [f'arn:{p}:bedrock:{auth.region}::foundation-model/{m}'
                  for m in (models or [DEFAULT_MODEL, EMBED_MODEL])]
    stmts = [{'Sid': 'InvokeNamedModels', 'Effect': 'Allow',
              'Action': ['bedrock:InvokeModel', 'bedrock:InvokeModelWithResponseStream',
                         'bedrock:Converse', 'bedrock:ConverseStream',
                         'bedrock:ApplyGuardrail'],
              'Resource': model_arns}]
    if bucket:
        b = auth.arn_for('s3', bucket, region='', account=False)
        stmts.append({'Sid': 'ReadStackBucket', 'Effect': 'Allow',
                      'Action': ['s3:GetObject', 's3:ListBucket'], 'Resource': [b, f'{b}/*']})
    if kms_key_arn:
        stmts.append({'Sid': 'UseStackKey', 'Effect': 'Allow',
                      'Action': ['kms:Decrypt', 'kms:DescribeKey', 'kms:GenerateDataKey'],
                      'Resource': kms_key_arn})
    if collection_arn:
        stmts.append({'Sid': 'QueryVectorStore', 'Effect': 'Allow',
                      'Action': 'aoss:APIAccessAll', 'Resource': collection_arn})
    return {'Version': '2012-10-17', 'Statement': stmts}

# %% ../nbs/01_ai.ipynb #e333ff4a
def _aoss_policies(auth, name, role_arns, kms_key_arn, public):
    'The three policies an AOSS collection needs before it will accept traffic.'
    res = [f'collection/{name}']
    enc = {'Rules': [{'ResourceType': 'collection', 'Resource': res}]}
    if kms_key_arn: enc['KmsARN'] = kms_key_arn
    else:           enc['AWSOwnedKey'] = True
    net = [{'Rules': [{'ResourceType': 'collection', 'Resource': res},
                      {'ResourceType': 'dashboard', 'Resource': res}],
            'AllowFromPublic': public}]
    access = [{'Rules': [{'ResourceType': 'collection', 'Resource': res,
                          'Permission': ['aoss:CreateCollectionItems', 'aoss:DescribeCollectionItems',
                                         'aoss:UpdateCollectionItems']},
                         {'ResourceType': 'index', 'Resource': [f'index/{name}/*'],
                          'Permission': ['aoss:CreateIndex', 'aoss:DescribeIndex', 'aoss:ReadDocument',
                                         'aoss:WriteDocument', 'aoss:UpdateIndex']}],
               'Principal': list(role_arns or []) + [auth.arn]}]
    return enc, net, access

def create_aoss_collection(auth, name, role_arns=None, kms_key_arn=None, public=False,
                           tags=None, **compliance_opts) -> dict:
    'Create an OpenSearch Serverless vector collection with its encryption, network, and access policies.'
    c = auth.client('opensearchserverless')
    enc, net, access = _aoss_policies(auth, name, role_arns, kms_key_arn, public)
    for kind, pol in (('encryption', enc), ('network', net)):
        try: c.create_security_policy(name=f'{name}-{kind}', type=kind, policy=json.dumps(pol))
        except c.exceptions.ConflictException: pass
    try: c.create_access_policy(name=f'{name}-access', type='data', policy=json.dumps(access))
    except c.exceptions.ConflictException: pass
    try:
        return c.create_collection(name=name, type='VECTORSEARCH',
                                   tags=tag_list(tags, 'key', 'value'))['createCollectionDetail']
    except c.exceptions.ConflictException:
        return c.batch_get_collection(names=[name])['collectionDetails'][0]

def aoss_endpoint(auth, name) -> str:
    'HTTPS endpoint of an AOSS collection.'
    d = auth.client('opensearchserverless').batch_get_collection(names=[name])['collectionDetails'][0]
    return d['collectionEndpoint']

# %% ../nbs/01_ai.ipynb #104d90e7
def create_kb(auth, name, bucket, role_arn, collection_arn, index=None, prefix='',
              embed_model=EMBED_MODEL, description=None, tags=None, **compliance_opts) -> dict:
    'Create a Bedrock Knowledge Base over an AOSS collection, with an S3 data source attached.'
    c = auth.client('bedrock-agent')
    index = index or f'{name}-index'
    kw = dict(name=name, roleArn=role_arn,
              description=description or f'awseasy knowledge base {name}',
              knowledgeBaseConfiguration={
                  'type': 'VECTOR',
                  'vectorKnowledgeBaseConfiguration': {
                      'embeddingModelArn':
                          f'arn:{auth.partition}:bedrock:{auth.region}::foundation-model/{embed_model}'}},
              storageConfiguration={
                  'type': 'OPENSEARCH_SERVERLESS',
                  'opensearchServerlessConfiguration': {
                      'collectionArn': collection_arn,
                      'vectorIndexName': index,
                      'fieldMapping': {'vectorField': 'embedding', 'textField': 'content',
                                       'metadataField': 'metadata'}}},
              tags=tags or {})
    kb = c.create_knowledge_base(**kw)['knowledgeBase']
    kb['dataSource'] = kb_data_source(auth, kb['knowledgeBaseId'], bucket, prefix)
    return kb

def kb_data_source(auth, kb_id, bucket, prefix='') -> dict:
    'Attach an S3 bucket (optionally one prefix of it) to a knowledge base as a data source.'
    s3 = {'bucketArn': auth.arn_for('s3', bucket, region='', account=False)}
    if prefix: s3['inclusionPrefixes'] = [prefix]
    return auth.client('bedrock-agent').create_data_source(
        knowledgeBaseId=kb_id, name=f'{kb_id}-s3',
        dataSourceConfiguration={'type': 'S3', 's3Configuration': s3})['dataSource']

def sync_kb(auth, kb_id, data_source_id) -> dict:
    'Start an ingestion job. Documents are not indexed until this runs.'
    return auth.client('bedrock-agent').start_ingestion_job(
        knowledgeBaseId=kb_id, dataSourceId=data_source_id)['ingestionJob']

# %% ../nbs/01_ai.ipynb #f4baca8c
def _password(n=24) -> str:
    'Password meeting the OpenSearch master-user rules: upper, lower, digit, and symbol.'
    pools = [string.ascii_uppercase, string.ascii_lowercase, string.digits, '!@#$%^&*()-_=+']
    chars = [secrets.choice(p) for p in pools]
    chars += [secrets.choice(''.join(pools)) for _ in range(n - len(pools))]
    secrets.SystemRandom().shuffle(chars)
    return ''.join(chars)

def create_opensearch(auth, name, engine_version='OpenSearch_2.13', instance_type='r6g.large.search',
                      instance_count=1, volume_size=20, master_user='os-admin', kms_key_id=None,
                      subnet_ids=None, sg_ids=None, audit=False, wait=False, tags=None,
                      **compliance_opts) -> dict:
    'Create an OpenSearch domain with TLS 1.2, encryption everywhere, and fine-grained access control.'
    c = auth.client('opensearch')
    password = _password()
    kw = dict(
        DomainName=name, EngineVersion=engine_version,
        ClusterConfig={'InstanceType': instance_type, 'InstanceCount': instance_count,
                       'ZoneAwarenessEnabled': instance_count > 1},
        EBSOptions={'EBSEnabled': True, 'VolumeType': 'gp3', 'VolumeSize': volume_size},
        EncryptionAtRestOptions={'Enabled': True, **({'KmsKeyId': kms_key_id} if kms_key_id else {})},
        NodeToNodeEncryptionOptions={'Enabled': True},
        DomainEndpointOptions={'EnforceHTTPS': True,
                               'TLSSecurityPolicy': 'Policy-Min-TLS-1-2-2019-07'},
        AdvancedSecurityOptions={'Enabled': True, 'InternalUserDatabaseEnabled': True,
                                 'MasterUserOptions': {'MasterUserName': master_user,
                                                       'MasterUserPassword': password}},
        TagList=tag_list(named(name, tags)))
    if subnet_ids: kw['VPCOptions'] = {'SubnetIds': subnet_ids, 'SecurityGroupIds': sg_ids or []}
    if audit:
        kw['LogPublishingOptions'] = {'AUDIT_LOGS': {
            'CloudWatchLogsLogGroupArn': auth.arn_for('logs', f'log-group:/aws/opensearch/{name}'),
            'Enabled': True}}
    try:
        domain = c.create_domain(**kw)['DomainStatus']
        # The only copy of the password leaves this process straight into Secrets Manager.
        create_secret(auth, f'opensearch/{name}/admin',
                      {'username': master_user, 'password': password},
                      kms_key_id=kms_key_id, description=f'OpenSearch master user for {name}')
    except c.exceptions.ResourceAlreadyExistsException:
        domain = c.describe_domain(DomainName=name)['DomainStatus']
    if wait:
        # OpenSearch has no boto3 waiter; Processing stays true until the domain settles.
        domain = poll_until(lambda: c.describe_domain(DomainName=name)['DomainStatus'],
                            lambda d: not d.get('Processing') and d.get('Endpoint'),
                            desc=f'OpenSearch domain {name}')
    return domain

def opensearch_endpoint(auth, name) -> str:
    'HTTPS endpoint of an OpenSearch domain.'
    d = auth.client('opensearch').describe_domain(DomainName=name)['DomainStatus']
    return f"https://{d['Endpoint']}"

def opensearch_admin_creds(auth, name) -> dict:
    'Master user credentials stored by create_opensearch, as {username, password}.'
    return get_secret(auth, f'opensearch/{name}/admin')
