"""Enterprise OAuth 2.0 / OIDC sign-in with Amazon Cognito: SSO federation, app clients, JWT verification, and ALB-enforced login.

Docs: https://vedicreader.github.io/awseasy/auth.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_auth.ipynb.

# %% auto #0
__all__ = ['PASSWORD_POLICY', 'GROUP_ATTR', 'SAML_ATTRS', 'OIDC_ATTRS', 'create_user_pool', 'user_pool_id', 'user_pool_arn',
           'issuer_url', 'jwks_url', 'create_pool_domain', 'domain_url', 'login_url', 'logout_url', 'token_url',
           'add_saml_idp', 'add_oidc_idp', 'add_entra_idp', 'add_okta_idp', 'add_google_idp', 'list_idps',
           'create_app_client', 'app_client_secret', 'create_resource_server', 'verify_jwt', 'check_claims',
           'token_groups', 'protect_listener', 'alb_cognito_rule', 'alb_oidc_rule']

# %% ../nbs/05_auth.ipynb #c21b5fd7
import json, time
from urllib.parse import urlencode, urlparse
from fastcore.all import L, first
from .core import tag_list

# %% ../nbs/05_auth.ipynb #9522e6f7
PASSWORD_POLICY = {'MinimumLength': 12, 'RequireUppercase': True, 'RequireLowercase': True,
                   'RequireNumbers': True, 'RequireSymbols': True,
                   'TemporaryPasswordValidityDays': 3}

def create_user_pool(auth, name, mfa_required=True, self_signup=False, threat_protection=True,
                     password_policy=None, deletion_protection=True, tags=None,
                     **compliance_opts) -> dict:
    'Create a Cognito user pool with enterprise defaults. Idempotent by pool name.'
    c = auth.client('cognito-idp')
    found = first(p for p in c.list_user_pools(MaxResults=60)['UserPools'] if p['Name'] == name)
    if found: return c.describe_user_pool(UserPoolId=found['Id'])['UserPool']
    pool = c.create_user_pool(
        PoolName=name,
        Policies={'PasswordPolicy': password_policy or PASSWORD_POLICY},
        # Federated or admin-created accounts only — the internet cannot sign itself up.
        AdminCreateUserConfig={'AllowAdminCreateUserOnly': not self_signup},
        UserPoolAddOns={'AdvancedSecurityMode': 'ENFORCED' if threat_protection else 'OFF'},
        DeletionProtection='ACTIVE' if deletion_protection else 'INACTIVE',
        AutoVerifiedAttributes=['email'],
        UsernameConfiguration={'CaseSensitive': False},
        AccountRecoverySetting={'RecoveryMechanisms': [{'Priority': 1, 'Name': 'verified_email'}]},
        UserPoolTags=tags or {})['UserPool']
    if mfa_required:
        # MFA cannot be set to ON at create time until a factor exists, so enable TOTP first.
        c.set_user_pool_mfa_config(UserPoolId=pool['Id'], MfaConfiguration='ON',
                                   SoftwareTokenMfaConfiguration={'Enabled': True})
    return c.describe_user_pool(UserPoolId=pool['Id'])['UserPool']

def user_pool_id(auth, name) -> str:
    'Look up a user pool id by name.'
    p = first(p for p in auth.client('cognito-idp').list_user_pools(MaxResults=60)['UserPools']
              if p['Name'] == name)
    if not p: raise ValueError(f'user pool {name!r} not found in {auth.region}')
    return p['Id']

def user_pool_arn(auth, pool_id) -> str:
    'ARN of a user pool, as required by ALB authenticate-cognito actions.'
    return auth.arn_for('cognito-idp', f'userpool/{pool_id}')

def issuer_url(auth, pool_id) -> str:
    'OIDC issuer for the pool — the `iss` claim on every token it mints.'
    return f'https://cognito-idp.{auth.region}.amazonaws.com/{pool_id}'

def jwks_url(auth, pool_id) -> str:
    'Public key set used to verify the pool\'s tokens.'
    return f'{issuer_url(auth, pool_id)}/.well-known/jwks.json'

# %% ../nbs/05_auth.ipynb #9795a8e7
def create_pool_domain(auth, pool_id, domain, cert_arn=None) -> dict:
    'Create the hosted-UI domain for a pool. Pass cert_arn for a custom domain (cert must be in us-east-1).'
    c = auth.client('cognito-idp')
    kw = {'Domain': domain, 'UserPoolId': pool_id}
    if cert_arn: kw['CustomDomainConfig'] = {'CertificateArn': cert_arn}
    try: c.create_user_pool_domain(**kw)
    except c.exceptions.InvalidParameterException as e:
        if 'already' not in str(e).lower(): raise
    return c.describe_user_pool_domain(Domain=domain)['DomainDescription']

def domain_url(auth, domain) -> str:
    'Base URL of a hosted-UI domain. A custom domain (one containing a dot) is used as given.'
    return domain if '.' in domain else f'https://{domain}.auth.{auth.region}.amazoncognito.com'

def login_url(auth, domain, client_id, redirect_uri, scopes=('openid', 'email', 'profile'),
              idp=None) -> str:
    'Authorization-code login URL. idp= sends the user straight to that IdP, skipping the chooser.'
    q = {'client_id': client_id, 'response_type': 'code', 'scope': ' '.join(scopes),
         'redirect_uri': redirect_uri}
    if idp: q['identity_provider'] = idp
    return f'{domain_url(auth, domain)}/oauth2/authorize?{urlencode(q)}'

def logout_url(auth, domain, client_id, redirect_uri) -> str:
    'Sign the user out of the Cognito session and return them to redirect_uri.'
    return f'{domain_url(auth, domain)}/logout?' + urlencode(
        {'client_id': client_id, 'logout_uri': redirect_uri})

def token_url(auth, domain) -> str:
    'Token endpoint, where the app exchanges an authorization code for tokens.'
    return f'{domain_url(auth, domain)}/oauth2/token'

# %% ../nbs/05_auth.ipynb #5ac4d717
GROUP_ATTR = {'entra': 'groups', 'okta': 'groups', 'google': 'groups', 'saml': 'groups'}
SAML_ATTRS = {
    'email': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
    'given_name': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname',
    'family_name': 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'}
OIDC_ATTRS = {'email': 'email', 'given_name': 'given_name', 'family_name': 'family_name'}

def _put_idp(auth, pool_id, name, kind, details, attr_map) -> dict:
    'Create or update an identity provider. Idempotent by provider name.'
    c = auth.client('cognito-idp')
    existing = {p['ProviderName'] for p in
                c.list_identity_providers(UserPoolId=pool_id, MaxResults=60)['Providers']}
    if name in existing:
        return c.update_identity_provider(UserPoolId=pool_id, ProviderName=name,
                                          ProviderDetails=details,
                                          AttributeMapping=attr_map)['IdentityProvider']
    return c.create_identity_provider(UserPoolId=pool_id, ProviderName=name, ProviderType=kind,
                                      ProviderDetails=details,
                                      AttributeMapping=attr_map)['IdentityProvider']

def add_saml_idp(auth, pool_id, name, metadata_url=None, metadata_file=None, attr_map=None,
                 idp_signout=True) -> dict:
    'Federate a SAML 2.0 IdP (ADFS, Entra ID SAML, Okta SAML, Ping, Shibboleth).'
    if not (metadata_url or metadata_file):
        raise ValueError('pass metadata_url= or metadata_file=')
    details = {'IDPSignout': 'true' if idp_signout else 'false'}
    if metadata_url: details['MetadataURL'] = metadata_url
    else:            details['MetadataFile'] = metadata_file
    return _put_idp(auth, pool_id, name, 'SAML', details, attr_map or SAML_ATTRS)

def add_oidc_idp(auth, pool_id, name, client_id, client_secret, issuer,
                 scopes='openid email profile', attr_map=None, method='GET') -> dict:
    'Federate any OIDC provider by issuer URL; endpoints are discovered from the issuer.'
    return _put_idp(auth, pool_id, name, 'OIDC', {
        'client_id': client_id, 'client_secret': client_secret, 'oidc_issuer': issuer,
        'authorize_scopes': scopes, 'attributes_request_method': method}, attr_map or OIDC_ATTRS)

def add_entra_idp(auth, pool_id, tenant_id, client_id, client_secret, name='EntraID',
                  attr_map=None) -> dict:
    'Federate Microsoft Entra ID (Azure AD) over OIDC for one tenant.'
    return add_oidc_idp(auth, pool_id, name, client_id, client_secret,
                        issuer=f'https://login.microsoftonline.com/{tenant_id}/v2.0',
                        attr_map=attr_map)

def add_okta_idp(auth, pool_id, okta_domain, client_id, client_secret, name='Okta',
                 attr_map=None) -> dict:
    'Federate Okta over OIDC. okta_domain is e.g. "acme.okta.com".'
    issuer = okta_domain if okta_domain.startswith('https://') else f'https://{okta_domain}'
    return add_oidc_idp(auth, pool_id, name, client_id, client_secret,
                        issuer=f'{issuer}/oauth2/default', attr_map=attr_map)

def add_google_idp(auth, pool_id, client_id, client_secret, name='Google',
                   scopes='openid email profile', attr_map=None) -> dict:
    'Federate Google Workspace.'
    return _put_idp(auth, pool_id, name, 'Google',
                    {'client_id': client_id, 'client_secret': client_secret,
                     'authorize_scopes': scopes},
                    attr_map or {'email': 'email', 'given_name': 'given_name',
                                 'family_name': 'family_name'})

def list_idps(auth, pool_id) -> list:
    'Identity provider names configured on a pool.'
    return [p['ProviderName'] for p in
            auth.client('cognito-idp').list_identity_providers(UserPoolId=pool_id,
                                                               MaxResults=60)['Providers']]

# %% ../nbs/05_auth.ipynb #2477e1a7
def _check_callbacks(urls):
    'Reject plaintext callbacks; localhost is allowed so local development still works.'
    for u in urls:
        p = urlparse(u)
        if p.scheme == 'https': continue
        if p.scheme == 'http' and p.hostname in ('localhost', '127.0.0.1'): continue
        raise ValueError(f'callback {u!r} must use https (http is allowed only on localhost)')

def create_app_client(auth, pool_id, name, callback_urls=None, logout_urls=None, idps=None,
                      scopes=('openid', 'email', 'profile'), generate_secret=True,
                      access_minutes=60, id_minutes=60, refresh_days=1, flows=('code',)) -> dict:
    'Create an OAuth app client restricted to the authorization-code flow. Idempotent by client name.'
    if 'implicit' in flows:
        raise ValueError('the implicit flow exposes tokens in the URL fragment; use flows=("code",)')
    callback_urls = list(callback_urls or [])
    _check_callbacks(callback_urls + list(logout_urls or []))
    c = auth.client('cognito-idp')
    found = first(cl for cl in c.list_user_pool_clients(UserPoolId=pool_id,
                                                        MaxResults=60)['UserPoolClients']
                  if cl['ClientName'] == name)
    if found:
        return c.describe_user_pool_client(UserPoolId=pool_id,
                                           ClientId=found['ClientId'])['UserPoolClient']
    return c.create_user_pool_client(
        UserPoolId=pool_id, ClientName=name, GenerateSecret=generate_secret,
        AllowedOAuthFlows=list(flows), AllowedOAuthScopes=list(scopes),
        AllowedOAuthFlowsUserPoolClient=True,
        CallbackURLs=callback_urls, LogoutURLs=list(logout_urls or []),
        SupportedIdentityProviders=list(idps or list_idps(auth, pool_id) or ['COGNITO']),
        # No USER_PASSWORD_AUTH: the application must never handle a user's password.
        ExplicitAuthFlows=['ALLOW_REFRESH_TOKEN_AUTH'],
        PreventUserExistenceErrors='ENABLED', EnableTokenRevocation=True,
        AccessTokenValidity=access_minutes, IdTokenValidity=id_minutes,
        RefreshTokenValidity=refresh_days,
        TokenValidityUnits={'AccessToken': 'minutes', 'IdToken': 'minutes',
                            'RefreshToken': 'days'})['UserPoolClient']

def app_client_secret(auth, pool_id, client_id) -> str:
    'Client secret for a confidential app client.'
    return auth.client('cognito-idp').describe_user_pool_client(
        UserPoolId=pool_id, ClientId=client_id)['UserPoolClient'].get('ClientSecret', '')

def create_resource_server(auth, pool_id, identifier, scopes, name=None) -> dict:
    'Declare API scopes for machine-to-machine access. scopes is {scope_name: description}.'
    return auth.client('cognito-idp').create_resource_server(
        UserPoolId=pool_id, Identifier=identifier, Name=name or identifier,
        Scopes=[{'ScopeName': k, 'ScopeDescription': v} for k, v in scopes.items()])['ResourceServer']

# %% ../nbs/05_auth.ipynb #7b02e7e6
def verify_jwt(auth, pool_id, token, client_id=None, use='id', jwks=None, leeway=10) -> dict:
    'Verify a Cognito JWT and return its claims. Raises jwt.InvalidTokenError if anything fails.'
    import jwt
    kid = jwt.get_unverified_header(token).get('kid')
    if jwks is not None:
        key = first(k for k in jwt.PyJWKSet.from_dict(jwks).keys if k.key_id == kid)
        if key is None: raise jwt.InvalidTokenError(f'no key {kid!r} in the supplied JWKS')
        key = key.key
    else:
        key = jwt.PyJWKClient(jwks_url(auth, pool_id)).get_signing_key_from_jwt(token).key
    claims = jwt.decode(token, key, algorithms=['RS256'], issuer=issuer_url(auth, pool_id),
                        leeway=leeway, options={'verify_aud': False,
                                                'require': ['exp', 'iss', 'token_use']})
    return check_claims(claims, client_id, use)

def check_claims(claims, client_id=None, use='id') -> dict:
    'Check token_use and audience on already-signature-verified claims. Returns the claims.'
    import jwt
    if use and claims.get('token_use') != use:
        raise jwt.InvalidTokenError(
            f"expected a {use!r} token, got {claims.get('token_use')!r}")
    if client_id:
        # ID tokens carry the app client in `aud`; access tokens carry it in `client_id`.
        got = claims.get('aud') if claims.get('token_use') == 'id' else claims.get('client_id')
        if got != client_id:
            raise jwt.InvalidTokenError(f'token was issued for {got!r}, not {client_id!r}')
    return claims

def token_groups(claims) -> list:
    'Group memberships from a token: the federated IdP groups, else the Cognito groups.'
    g = claims.get('custom:groups') or claims.get('cognito:groups') or []
    return json.loads(g) if isinstance(g, str) and g.startswith('[') else L(g).map(str) if g else []

# %% ../nbs/05_auth.ipynb #5fbb68fc
def _cognito_action(pool_arn, client_id, domain, scope, session_timeout, order=1) -> dict:
    return {'Type': 'authenticate-cognito', 'Order': order, 'AuthenticateCognitoConfig': {
        'UserPoolArn': pool_arn, 'UserPoolClientId': client_id, 'UserPoolDomain': domain,
        'Scope': scope, 'SessionTimeout': session_timeout,
        'SessionCookieName': 'AWSELBAuthSessionCookie',
        'OnUnauthenticatedRequest': 'authenticate'}}

def _oidc_action(issuer, client_id, client_secret, endpoints, scope, session_timeout,
                 order=1) -> dict:
    cfg = {'Issuer': issuer, 'ClientId': client_id, 'ClientSecret': client_secret,
           'Scope': scope, 'SessionTimeout': session_timeout,
           'SessionCookieName': 'AWSELBAuthSessionCookie',
           'OnUnauthenticatedRequest': 'authenticate'}
    cfg.update({'AuthorizationEndpoint': endpoints['authorization'],
                'TokenEndpoint': endpoints['token'],
                'UserInfoEndpoint': endpoints['userinfo']})
    return {'Type': 'authenticate-oidc', 'Order': order, 'AuthenticateOidcConfig': cfg}

def protect_listener(auth, listener_arn, target_group_arn, pool_arn, client_id, domain,
                     scope='openid', session_timeout=3600) -> dict:
    'Require Cognito sign-in for every request on a listener. Leaves no unauthenticated path.'
    return auth.client('elbv2').modify_listener(
        ListenerArn=listener_arn,
        DefaultActions=[_cognito_action(pool_arn, client_id, domain, scope, session_timeout),
                        {'Type': 'forward', 'Order': 2,
                         'TargetGroupArn': target_group_arn}])['Listeners'][0]

def alb_cognito_rule(auth, listener_arn, target_group_arn, pool_arn, client_id, domain,
                     paths=('/*',), priority=1, scope='openid', session_timeout=3600) -> dict:
    'Require Cognito sign-in for requests matching `paths` on a listener.'
    return auth.client('elbv2').create_rule(
        ListenerArn=listener_arn, Priority=priority,
        Conditions=[{'Field': 'path-pattern', 'Values': list(paths)}],
        Actions=[_cognito_action(pool_arn, client_id, domain, scope, session_timeout),
                 {'Type': 'forward', 'Order': 2, 'TargetGroupArn': target_group_arn}])['Rules'][0]

def alb_oidc_rule(auth, listener_arn, target_group_arn, issuer, client_id, client_secret,
                  endpoints, paths=('/*',), priority=1, scope='openid email',
                  session_timeout=3600) -> dict:
    '''Authenticate at the ALB against any OIDC provider directly, bypassing Cognito.

    `endpoints` is {authorization, token, userinfo} — take them from the IdP's
    /.well-known/openid-configuration document.'''
    missing = {'authorization', 'token', 'userinfo'} - set(endpoints)
    if missing: raise ValueError(f'endpoints is missing {sorted(missing)}')
    return auth.client('elbv2').create_rule(
        ListenerArn=listener_arn, Priority=priority,
        Conditions=[{'Field': 'path-pattern', 'Values': list(paths)}],
        Actions=[_oidc_action(issuer, client_id, client_secret, endpoints, scope, session_timeout),
                 {'Type': 'forward', 'Order': 2, 'TargetGroupArn': target_group_arn}])['Rules'][0]
