"""CloudFront distributions, AWS WAF, ACM certificates, and Route 53 aliases — the public edge of a GenAI app.

Docs: https://vedicreader.github.io/awseasy/cdn.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_cdn.ipynb.

# %% auto #0
__all__ = ['CF_HOSTED_ZONE', 'MANAGED_RULES', 'CACHE_OPTIMIZED', 'CACHE_DISABLED', 'ALL_VIEWER_EXCEPT_HOST', 'READ_METHODS',
           'ALL_METHODS', 'request_cert', 'cert_validation_records', 'cert_status', 'create_oac', 's3_oac_policy',
           'security_headers_policy', 'waf_rules', 'create_waf', 'distribution_config', 'create_distribution',
           'distribution_domain', 'invalidate', 'alias_record', 'zone_id']

# %% ../nbs/06_cdn.ipynb #32f140f0
import json, time
from fastcore.all import L, first
from .core import tag_list, wait_for

# %% ../nbs/06_cdn.ipynb #c789dc87
CF_HOSTED_ZONE = 'Z2FDTNDATAQYW2'   # fixed, global: every CloudFront alias target uses this

def request_cert(auth, domain, alt_names=None, region='us-east-1', validation='DNS',
                 wait=False, tags=None) -> str:
    '''Request an ACM certificate and return its ARN. Defaults to us-east-1, as CloudFront requires.

    `wait=True` blocks until the certificate is ISSUED, which only happens once the DNS records
    from `cert_validation_records()` are published — so publish them first, or this will time out.'''
    kw = dict(DomainName=domain, ValidationMethod=validation,
              Options={'CertificateTransparencyLoggingPreference': 'ENABLED'},
              Tags=tag_list(tags) or [{'Key': 'Name', 'Value': domain}])
    if alt_names: kw['SubjectAlternativeNames'] = list(alt_names)
    c = auth.client('acm', region=region)
    arn = c.request_certificate(**kw)['CertificateArn']
    if wait: wait_for(c, 'certificate_validated', delay=20, attempts=60, CertificateArn=arn)
    return arn

def cert_validation_records(auth, cert_arn, region='us-east-1') -> list:
    'CNAME records to publish so ACM can validate the certificate. Empty until ACM populates them.'
    c = auth.client('acm', region=region).describe_certificate(CertificateArn=cert_arn)['Certificate']
    return [v['ResourceRecord'] for v in c.get('DomainValidationOptions', [])
            if v.get('ResourceRecord')]

def cert_status(auth, cert_arn, region='us-east-1') -> str:
    'PENDING_VALIDATION, ISSUED, FAILED, ...'
    return auth.client('acm', region=region).describe_certificate(
        CertificateArn=cert_arn)['Certificate']['Status']

# %% ../nbs/06_cdn.ipynb #4d579e01
def create_oac(auth, name, kind='s3') -> str:
    'Create (or find) an origin access control and return its id.'
    c = auth.client('cloudfront', region='us-east-1')
    found = first(o for o in c.list_origin_access_controls().get(
        'OriginAccessControlList', {}).get('Items', []) if o['Name'] == name)
    if found: return found['Id']
    return c.create_origin_access_control(OriginAccessControlConfig={
        'Name': name, 'Description': f'awseasy OAC for {name}',
        'SigningProtocol': 'sigv4', 'SigningBehavior': 'always',
        'OriginAccessControlOriginType': kind})['OriginAccessControl']['Id']

def s3_oac_policy(auth, bucket, distribution_arn, sid='AllowCloudFrontOAC'):
    'Let one CloudFront distribution — and nothing else — read the bucket. Merges with any existing policy.'
    s3 = auth.client('s3')
    try: policy = json.loads(s3.get_bucket_policy(Bucket=bucket)['Policy'])
    except s3.exceptions.ClientError: policy = {'Version': '2012-10-17', 'Statement': []}
    stmt = {'Sid': sid, 'Effect': 'Allow',
            'Principal': {'Service': 'cloudfront.amazonaws.com'},
            'Action': 's3:GetObject',
            'Resource': f"{auth.arn_for('s3', bucket, region='', account=False)}/*",
            'Condition': {'StringEquals': {'AWS:SourceArn': distribution_arn}}}
    policy['Statement'] = [s for s in policy['Statement'] if s.get('Sid') != sid] + [stmt]
    s3.put_bucket_policy(Bucket=bucket, Policy=json.dumps(policy))
    return policy

# %% ../nbs/06_cdn.ipynb #ae2da065
def security_headers_policy(auth, name, csp=None, hsts_seconds=63072000,
                            frame_option='DENY', referrer='strict-origin-when-cross-origin') -> str:
    'Create a response headers policy with the standard security headers. Returns its id.'
    c = auth.client('cloudfront', region='us-east-1')
    found = first(p for p in c.list_response_headers_policies().get(
        'ResponseHeadersPolicyList', {}).get('Items', [])
        if p['ResponseHeadersPolicy']['ResponseHeadersPolicyConfig']['Name'] == name)
    if found: return found['ResponseHeadersPolicy']['Id']
    sec = {
        'StrictTransportSecurity': {'Override': True, 'AccessControlMaxAgeSec': hsts_seconds,
                                    'IncludeSubdomains': True, 'Preload': True},
        'ContentTypeOptions': {'Override': True},
        'FrameOptions': {'Override': True, 'FrameOption': frame_option},
        'ReferrerPolicy': {'Override': True, 'ReferrerPolicy': referrer},
        'XSSProtection': {'Override': True, 'Protection': True, 'ModeBlock': True}}
    if csp: sec['ContentSecurityPolicy'] = {'Override': True, 'ContentSecurityPolicy': csp}
    return c.create_response_headers_policy(ResponseHeadersPolicyConfig={
        'Name': name, 'Comment': f'awseasy security headers for {name}',
        'SecurityHeadersConfig': sec})['ResponseHeadersPolicy']['Id']

# %% ../nbs/06_cdn.ipynb #0b2e85c3
MANAGED_RULES = ['AWSManagedRulesCommonRuleSet', 'AWSManagedRulesKnownBadInputsRuleSet',
                 'AWSManagedRulesAmazonIpReputationList', 'AWSManagedRulesSQLiRuleSet']

def _vis(name): return {'SampledRequestsEnabled': True, 'CloudWatchMetricsEnabled': True,
                        'MetricName': name.replace('_', '-')}

def waf_rules(managed_rules=None, rate_limit=2000) -> list:
    'Managed rule groups plus a rate-based rule, numbered in priority order.'
    rules = [{'Name': r, 'Priority': i,
              'Statement': {'ManagedRuleGroupStatement': {'VendorName': 'AWS', 'Name': r}},
              'OverrideAction': {'None': {}}, 'VisibilityConfig': _vis(r)}
             for i, r in enumerate(managed_rules if managed_rules is not None else MANAGED_RULES)]
    if rate_limit:
        rules.append({'Name': 'RateLimit', 'Priority': len(rules),
                      'Statement': {'RateBasedStatement': {'Limit': rate_limit,
                                                           'AggregateKeyType': 'IP'}},
                      'Action': {'Block': {}}, 'VisibilityConfig': _vis('RateLimit')})
    return rules

def create_waf(auth, name, scope='CLOUDFRONT', managed_rules=None, rate_limit=2000,
               tags=None) -> dict:
    'Create a web ACL with AWS managed rule groups and per-IP rate limiting. Idempotent by name.'
    region = 'us-east-1' if scope == 'CLOUDFRONT' else auth.region
    c = auth.client('wafv2', region=region)
    found = first(w for w in c.list_web_acls(Scope=scope)['WebACLs'] if w['Name'] == name)
    if found: return found
    kw = dict(Name=name, Scope=scope, DefaultAction={'Allow': {}},
              Description=f'awseasy web ACL for {name}',
              Rules=waf_rules(managed_rules, rate_limit), VisibilityConfig=_vis(name))
    if tags: kw['Tags'] = tag_list(tags)   # wafv2 rejects an empty tag list
    return c.create_web_acl(**kw)['Summary']

# %% ../nbs/06_cdn.ipynb #e6e70d94
CACHE_OPTIMIZED = '658327ea-f89d-4fab-a63d-7e88639e58f6'   # AWS managed: CachingOptimized
CACHE_DISABLED = '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'    # AWS managed: CachingDisabled
ALL_VIEWER_EXCEPT_HOST = 'b689b0a8-53d0-40ab-baf2-68738e2966ac'   # managed origin request policy
READ_METHODS = ['GET', 'HEAD', 'OPTIONS']
ALL_METHODS = ['GET', 'HEAD', 'OPTIONS', 'PUT', 'POST', 'PATCH', 'DELETE']

def _methods(kind):
    items = ALL_METHODS if kind == 'all' else READ_METHODS
    return {'Quantity': len(items), 'Items': items,
            'CachedMethods': {'Quantity': 2, 'Items': ['GET', 'HEAD']}}

def distribution_config(auth, name, origin_domain=None, s3_bucket=None, oac_id=None, domains=None,
                        cert_arn=None, waf_acl_arn=None, headers_policy_id=None,
                        cache_policy=CACHE_OPTIMIZED, origin_request_policy_id=None,
                        log_bucket=None, price_class='PriceClass_100', methods='read',
                        default_root='index.html', comment=None, **compliance_opts) -> dict:
    'Build the DistributionConfig. Separated out so the security settings can be asserted directly.'
    if bool(origin_domain) == bool(s3_bucket):
        raise ValueError('pass exactly one of origin_domain= or s3_bucket=')
    if domains and not cert_arn:
        raise ValueError('domains= needs cert_arn= (an ACM certificate in us-east-1)')
    origin = {'Id': 'origin-1'}
    if s3_bucket:
        origin['DomainName'] = f'{s3_bucket}.s3.{auth.region}.amazonaws.com'
        origin['S3OriginConfig'] = {'OriginAccessIdentity': ''}
        origin['OriginAccessControlId'] = oac_id
    else:
        origin['DomainName'] = origin_domain
        origin['CustomOriginConfig'] = {
            'HTTPPort': 80, 'HTTPSPort': 443, 'OriginProtocolPolicy': 'https-only',
            'OriginSslProtocols': {'Quantity': 1, 'Items': ['TLSv1.2']},
            'OriginReadTimeout': 60, 'OriginKeepaliveTimeout': 5}
    behavior = {'TargetOriginId': 'origin-1', 'ViewerProtocolPolicy': 'redirect-to-https',
                'CachePolicyId': cache_policy, 'AllowedMethods': _methods(methods),
                'Compress': True}
    if headers_policy_id: behavior['ResponseHeadersPolicyId'] = headers_policy_id
    if origin_request_policy_id: behavior['OriginRequestPolicyId'] = origin_request_policy_id
    cfg = {
        'CallerReference': f'awseasy-{name}', 'Comment': comment or name, 'Enabled': True,
        'Origins': {'Quantity': 1, 'Items': [origin]},
        'DefaultCacheBehavior': behavior,
        'HttpVersion': 'http2and3', 'IsIPV6Enabled': True, 'PriceClass': price_class,
        'ViewerCertificate': {'CloudFrontDefaultCertificate': True},
        'Logging': {'Enabled': False, 'IncludeCookies': False, 'Bucket': '', 'Prefix': ''}}
    if default_root: cfg['DefaultRootObject'] = default_root
    if domains:
        cfg['Aliases'] = {'Quantity': len(domains), 'Items': list(domains)}
        cfg['ViewerCertificate'] = {'ACMCertificateArn': cert_arn, 'SSLSupportMethod': 'sni-only',
                                    'MinimumProtocolVersion': 'TLSv1.2_2021',
                                    'CertificateSource': 'acm'}
    if waf_acl_arn: cfg['WebACLId'] = waf_acl_arn
    if log_bucket:
        cfg['Logging'] = {'Enabled': True, 'IncludeCookies': False,
                          'Bucket': f'{log_bucket}.s3.amazonaws.com', 'Prefix': f'{name}/'}
    return cfg

def _find_distribution(client, caller_ref):
    '''Find the distribution holding a CallerReference.

    Only runs on the collision path, so the extra get_distribution per distribution is paid once
    on a re-run rather than on every call. CallerReference is the exact thing that collided, which
    makes it a more reliable key than comparing comments or origin domains.'''
    for s in client.list_distributions()['DistributionList'].get('Items', []):
        d = client.get_distribution(Id=s['Id'])['Distribution']
        if d['DistributionConfig']['CallerReference'] == caller_ref: return d
    raise ValueError(f'CallerReference {caller_ref!r} is in use by a distribution this account '
                     'cannot see; pass a different name')

def create_distribution(auth, name, origin_domain=None, s3_bucket=None, oac_id=None, tags=None,
                        wait=False, **kw) -> dict:
    '''Create a hardened CloudFront distribution. Idempotent by name; wires OAC for S3 origins.

    A distribution takes several minutes to reach every edge location. `wait=True` blocks until
    it is Deployed — otherwise requests to it 404 for a while after this call returns.'''
    c = auth.client('cloudfront', region='us-east-1')
    if s3_bucket and not oac_id: oac_id = create_oac(auth, f'{name}-oac')
    cfg = distribution_config(auth, name, origin_domain=origin_domain, s3_bucket=s3_bucket,
                              oac_id=oac_id, **kw)
    try:
        dist = c.create_distribution_with_tags(DistributionConfigWithTags={
            'DistributionConfig': cfg, 'Tags': {'Items': tag_list(tags)}})['Distribution']
    except c.exceptions.DistributionAlreadyExists:
        dist = _find_distribution(c, cfg['CallerReference'])
    if s3_bucket: s3_oac_policy(auth, s3_bucket, dist['ARN'])
    if wait:
        wait_for(c, 'distribution_deployed', delay=30, attempts=60, Id=dist['Id'])
        dist = c.get_distribution(Id=dist['Id'])['Distribution']
    return dist

def distribution_domain(auth, dist_id) -> str:
    'The *.cloudfront.net domain of a distribution.'
    return auth.client('cloudfront', region='us-east-1').get_distribution(
        Id=dist_id)['Distribution']['DomainName']

def invalidate(auth, dist_id, paths=('/*',)) -> dict:
    'Invalidate cached paths. The first 1,000 paths each month are free.'
    return auth.client('cloudfront', region='us-east-1').create_invalidation(
        DistributionId=dist_id,
        InvalidationBatch={'Paths': {'Quantity': len(paths), 'Items': list(paths)},
                           'CallerReference': f'awseasy-{int(time.time() * 1000)}'})['Invalidation']

# %% ../nbs/06_cdn.ipynb #af6297b0
def alias_record(auth, zone_id, name, target, target_zone=CF_HOSTED_ZONE, kind='A') -> dict:
    'Point a name at CloudFront (or an ALB) with an alias record. Upsert, so it is safe to re-run.'
    return auth.client('route53').change_resource_record_sets(
        HostedZoneId=zone_id,
        ChangeBatch={'Comment': f'awseasy alias for {name}', 'Changes': [{
            'Action': 'UPSERT',
            'ResourceRecordSet': {'Name': name, 'Type': kind,
                                  'AliasTarget': {'HostedZoneId': target_zone, 'DNSName': target,
                                                  'EvaluateTargetHealth': False}}}]})['ChangeInfo']

def zone_id(auth, domain) -> str:
    'Hosted zone id for a domain.'
    domain = domain if domain.endswith('.') else f'{domain}.'
    z = first(z for z in auth.client('route53').list_hosted_zones()['HostedZones']
              if z['Name'] == domain)
    if not z: raise ValueError(f'no Route 53 hosted zone for {domain!r}')
    return z['Id'].split('/')[-1]
