"""EC2 instances, EKS clusters, and ECR registries for serving GenAI workloads.

Docs: https://vedicreader.github.io/awseasy/compute.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_compute.ipynb.

# %% auto #0
__all__ = ['UBUNTU_OWNER', 'UBUNTU_SSM', 'EKS_LOG_TYPES', 'latest_ubuntu_ami', 'create_instance', 'instance_ip', 'start_instance',
           'stop_instance', 'terminate_instance', 'create_eks', 'scale_eks', 'eks_kubeconfig', 'create_ecr',
           'ecr_lifecycle', 'ecr_uri', 'image_tags']

# %% ../nbs/03_compute.ipynb #7c307457
import json, subprocess
from fastcore.all import L, first
from .core import aws_policy, named, tag_list, wait_for
from .network import attach_policy, create_role

# %% ../nbs/03_compute.ipynb #007731ad
UBUNTU_OWNER = '099720109477'   # Canonical
UBUNTU_SSM = '/aws/service/canonical/ubuntu/server/{ver}/stable/current/amd64/hvm/ebs-gp3/ami-id'

def latest_ubuntu_ami(auth, ver='22.04') -> str:
    'Latest Canonical Ubuntu LTS AMI id, via the SSM public parameter with a describe_images fallback.'
    try: return auth.client('ssm').get_parameter(Name=UBUNTU_SSM.format(ver=ver))['Parameter']['Value']
    except Exception: pass
    imgs = auth.client('ec2').describe_images(Owners=[UBUNTU_OWNER], Filters=[
        {'Name': 'name', 'Values': [f'ubuntu/images/hvm-ssd*/ubuntu-*-{ver}-amd64-server-*']},
        {'Name': 'architecture', 'Values': ['x86_64']},
        {'Name': 'state', 'Values': ['available']}])['Images']
    if not imgs: raise ValueError(f'no Ubuntu {ver} AMI found in {auth.region}; pass ami= explicitly')
    return sorted(imgs, key=lambda i: i['CreationDate'])[-1]['ImageId']

def create_instance(auth, name, instance_type='t3.medium', ami=None, key_name=None, subnet_id=None,
                    sg_ids=None, iam_instance_profile=None, user_data=None, volume_size=30,
                    kms_key_id=None, wait=False, tags=None, **compliance_opts) -> dict:
    'Launch an EC2 instance with IMDSv2 required and an encrypted root volume.'
    ec2 = auth.client('ec2')
    ebs = {'VolumeSize': volume_size, 'VolumeType': 'gp3', 'Encrypted': True,
           'DeleteOnTermination': True}
    if kms_key_id: ebs['KmsKeyId'] = kms_key_id
    kw = dict(ImageId=ami or latest_ubuntu_ami(auth), InstanceType=instance_type, MinCount=1, MaxCount=1,
              # IMDSv2 only: an SSRF bug can no longer read the instance role's credentials
              MetadataOptions={'HttpTokens': 'required', 'HttpEndpoint': 'enabled',
                               'HttpPutResponseHopLimit': 1, 'InstanceMetadataTags': 'enabled'},
              BlockDeviceMappings=[{'DeviceName': '/dev/sda1', 'Ebs': ebs}],
              Monitoring={'Enabled': bool(compliance_opts.get('audit'))},
              TagSpecifications=[{'ResourceType': t, 'Tags': tag_list(named(name, tags))}
                                 for t in ('instance', 'volume')])
    if key_name: kw['KeyName'] = key_name
    if subnet_id: kw['SubnetId'] = subnet_id
    if sg_ids: kw['SecurityGroupIds'] = sg_ids
    if user_data: kw['UserData'] = user_data
    if iam_instance_profile: kw['IamInstanceProfile'] = {'Name': iam_instance_profile}
    inst = ec2.run_instances(**kw)['Instances'][0]
    if wait:
        wait_for(ec2, 'instance_running', delay=5, attempts=60, InstanceIds=[inst['InstanceId']])
        inst = ec2.describe_instances(
            InstanceIds=[inst['InstanceId']])['Reservations'][0]['Instances'][0]
    return inst

def instance_ip(auth, instance_id) -> str:
    'Public IP if the instance has one, otherwise the private IP.'
    i = auth.client('ec2').describe_instances(
        InstanceIds=[instance_id])['Reservations'][0]['Instances'][0]
    return i.get('PublicIpAddress') or i.get('PrivateIpAddress', '')

def start_instance(auth, instance_id): auth.client('ec2').start_instances(InstanceIds=[instance_id])
def stop_instance(auth, instance_id):  auth.client('ec2').stop_instances(InstanceIds=[instance_id])
def terminate_instance(auth, instance_id): auth.client('ec2').terminate_instances(InstanceIds=[instance_id])

# %% ../nbs/03_compute.ipynb #150bc14e
EKS_LOG_TYPES = ['api', 'audit', 'authenticator', 'controllerManager', 'scheduler']

def create_eks(auth, name, subnet_ids, node_type='m5.large', node_count=2, version='1.31',
               sg_ids=None, kms_key_id=None, public_access=True, public_cidrs=None,
               audit=False, wait=False, tags=None, **compliance_opts) -> dict:
    'Create an EKS cluster and managed node group, with secrets encryption and audit logging.'
    c = auth.client('eks')
    cluster_role = create_role(auth, f'{name}-eks-cluster-role', service='eks.amazonaws.com')
    attach_policy(auth, f'{name}-eks-cluster-role', aws_policy(auth, 'AmazonEKSClusterPolicy'))
    node_role = create_role(auth, f'{name}-eks-node-role', service='ec2.amazonaws.com')
    for p in ('AmazonEKSWorkerNodePolicy', 'AmazonEKS_CNI_Policy', 'AmazonEC2ContainerRegistryReadOnly'):
        attach_policy(auth, f'{name}-eks-node-role', aws_policy(auth, p))

    vpc_cfg = {'subnetIds': subnet_ids, 'endpointPrivateAccess': True,
               'endpointPublicAccess': public_access}
    if sg_ids: vpc_cfg['securityGroupIds'] = sg_ids
    if public_access and public_cidrs: vpc_cfg['publicAccessCidrs'] = public_cidrs
    kw = dict(name=name, version=version, roleArn=cluster_role['Role']['Arn'],
              resourcesVpcConfig=vpc_cfg, tags=tags or {})
    if kms_key_id:
        # Only settable at creation: without it, Kubernetes Secrets sit in etcd under an AWS-owned key.
        kw['encryptionConfig'] = [{'resources': ['secrets'], 'provider': {'keyArn': kms_key_id}}]
    if audit: kw['logging'] = {'clusterLogging': [{'types': EKS_LOG_TYPES, 'enabled': True}]}
    try: cluster = c.create_cluster(**kw)['cluster']
    except c.exceptions.ResourceInUseException:
        cluster = c.describe_cluster(name=name)['cluster']
    try:
        c.create_nodegroup(clusterName=name, nodegroupName=f'{name}-ng', subnets=subnet_ids,
                           instanceTypes=[node_type], nodeRole=node_role['Role']['Arn'],
                           scalingConfig={'minSize': 1, 'maxSize': max(node_count * 2, 2),
                                          'desiredSize': node_count})
    except c.exceptions.ResourceInUseException: pass
    if wait:
        # A cluster is ~10 minutes and the node group another ~5, so both need the raised ceiling.
        wait_for(c, 'cluster_active', name=name)
        wait_for(c, 'nodegroup_active', clusterName=name, nodegroupName=f'{name}-ng')
        cluster = c.describe_cluster(name=name)['cluster']
    return cluster

def scale_eks(auth, name, node_count, nodegroup=None):
    'Set the desired node count on a managed node group.'
    auth.client('eks').update_nodegroup_config(
        clusterName=name, nodegroupName=nodegroup or f'{name}-ng',
        scalingConfig={'desiredSize': node_count})

def eks_kubeconfig(auth, name, dry_run=True) -> str:
    'Run `aws eks update-kubeconfig`. Requires the AWS CLI; dry_run prints the config instead of writing it.'
    cmd = ['aws', 'eks', 'update-kubeconfig', '--name', name, '--region', auth.region]
    r = subprocess.run(cmd + (['--dry-run'] if dry_run else []), capture_output=True, text=True)
    if r.returncode: raise RuntimeError(f'aws eks update-kubeconfig failed: {r.stderr.strip()}')
    return r.stdout

# %% ../nbs/03_compute.ipynb #f379d1d6
def create_ecr(auth, name, scan_on_push=True, immutable=True, kms_key_id=None,
               max_untagged=10, tags=None, **compliance_opts) -> dict:
    'Create an ECR repository with scan-on-push, immutable tags, and an untagged-image lifecycle rule.'
    c = auth.client('ecr')
    enc = ({'encryptionType': 'KMS', 'kmsKey': kms_key_id} if kms_key_id
           else {'encryptionType': 'AES256'})
    try:
        repo = c.create_repository(
            repositoryName=name, imageScanningConfiguration={'scanOnPush': scan_on_push},
            imageTagMutability='IMMUTABLE' if immutable else 'MUTABLE',
            encryptionConfiguration=enc, tags=tag_list(tags))['repository']
    except c.exceptions.RepositoryAlreadyExistsException:
        repo = c.describe_repositories(repositoryNames=[name])['repositories'][0]
    if max_untagged: ecr_lifecycle(auth, name, max_untagged)
    return repo

def ecr_lifecycle(auth, name, max_untagged=10, keep_tagged=50) -> dict:
    'Expire untagged images beyond `max_untagged` and cap retained tagged images.'
    policy = {'rules': [
        {'rulePriority': 1, 'description': 'expire untagged images',
         'selection': {'tagStatus': 'untagged', 'countType': 'imageCountMoreThan',
                       'countNumber': max_untagged},
         'action': {'type': 'expire'}},
        {'rulePriority': 2, 'description': 'cap retained tagged images',
         'selection': {'tagStatus': 'any', 'countType': 'imageCountMoreThan',
                       'countNumber': keep_tagged},
         'action': {'type': 'expire'}}]}
    return auth.client('ecr').put_lifecycle_policy(repositoryName=name,
                                                   lifecyclePolicyText=json.dumps(policy))

def ecr_uri(auth, name, tag=None) -> str:
    'Registry URI for docker push/pull, optionally with a tag.'
    uri = f'{auth.account_id}.dkr.ecr.{auth.region}.amazonaws.com/{name}'
    return f'{uri}:{tag}' if tag else uri

def image_tags(auth, name) -> list:
    'Tags currently present in a repository.'
    imgs = auth.client('ecr').list_images(repositoryName=name)['imageIds']
    return [i['imageTag'] for i in imgs if 'imageTag' in i]
