"""Credentials, compliance profiles, tagging, KMS keys, resource groups, and the `GenAIStack` orchestrator.

Docs: https://vedicreader.github.io/awseasy/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['COMPLIANCE_KEYS', 'HIPAA', 'ISO27001', 'SOC2', 'PROFILES', 'Compliance', 'AWSAuth', 'aws_policy', 'tag_list',
           'tag_dict', 'named', 'create_kms_key', 'kms_key_arn', 'wait_for', 'poll_until', 'resource_group',
           'resource_group_query', 'list_resource_groups', 'delete_resource_group', 'GenAIStack', 'repo_root',
           'mv_skill_md']

# %% ../nbs/00_core.ipynb #de584757
import json, os, time, boto3
from fastcore.all import L, Path, first

# %% ../nbs/00_core.ipynb #ebb6c159
COMPLIANCE_KEYS = {'encryption', 'cmk', 'tls_min', 'audit', 'multi_az', 'backup_retention',
                   'deletion_protection', 'mfa_required', 'least_privilege', 'public_access', 'tags'}

class Compliance(dict):
    'Validated bundle of security controls. Unknown keys raise rather than silently doing nothing.'
    def __init__(self, **kw):
        bad = set(kw) - COMPLIANCE_KEYS
        if bad: raise ValueError(f'unknown compliance keys {sorted(bad)}; valid keys are {sorted(COMPLIANCE_KEYS)}')
        super().__init__(**kw)
    def __or__(self, other): return Compliance(**{**self, **other})
    def __repr__(self): return f'Compliance({", ".join(f"{k}={v!r}" for k,v in self.items())})'

HIPAA = Compliance(
    encryption=True, cmk=True, tls_min='1.2', audit=True, multi_az=True,
    backup_retention=35, deletion_protection=True, public_access=False,
    least_privilege=True, tags={'compliance': 'hipaa'})

ISO27001 = Compliance(
    encryption=True, cmk=True, tls_min='1.2', audit=True, least_privilege=True,
    backup_retention=14, public_access=False, tags={'compliance': 'iso27001'})

SOC2 = Compliance(
    encryption=True, tls_min='1.2', audit=True, mfa_required=True, least_privilege=True,
    backup_retention=7, public_access=False, tags={'compliance': 'soc2'})

PROFILES = dict(hipaa=HIPAA, iso27001=ISO27001, soc2=SOC2)

# %% ../nbs/00_core.ipynb #dc8a7513
class AWSAuth:
    'boto3 Session over the standard AWS credential chain, with cached per-service clients.'
    def __init__(self, region=None, profile=None, role_arn=None, session_name='awseasy'):
        region = region or os.environ.get('AWS_DEFAULT_REGION') or os.environ.get('AWS_REGION') or 'us-east-1'
        self.session = boto3.Session(profile_name=profile, region_name=region)
        if role_arn:
            c = self.session.client('sts').assume_role(
                RoleArn=role_arn, RoleSessionName=session_name)['Credentials']
            self.session = boto3.Session(
                aws_access_key_id=c['AccessKeyId'], aws_secret_access_key=c['SecretAccessKey'],
                aws_session_token=c['SessionToken'], region_name=region)
        self.region, self._clients, self._ident = region, {}, None

    def client(self, svc, region=None):
        'Cached client. Pass region to override — CloudFront certs and WAF ACLs must live in us-east-1.'
        k = (svc, region or self.region)
        if k not in self._clients: self._clients[k] = self.session.client(svc, region_name=k[1])
        return self._clients[k]

    def resource(self, svc): return self.session.resource(svc, region_name=self.region)

    @property
    def identity(self) -> dict:
        'sts:GetCallerIdentity, called once and cached.'
        if self._ident is None: self._ident = self.client('sts').get_caller_identity()
        return self._ident

    @property
    def account_id(self) -> str: return self.identity['Account']

    @property
    def arn(self) -> str: return self.identity['Arn']

    @property
    def partition(self) -> str:
        'ARN partition — aws, aws-us-gov, or aws-cn. GovCloud and China build different ARNs.'
        return self.arn.split(':')[1]

    def arn_for(self, svc, resource, region=None, account=True) -> str:
        'Build an ARN in this partition/account. region="" for global services (IAM, S3).'
        return f'arn:{self.partition}:{svc}:{self.region if region is None else region}:' \
               f'{self.account_id if account else ""}:{resource}'

    def __repr__(self): return f'AWSAuth(region={self.region!r})'

def aws_policy(auth, name) -> str:
    'ARN of an AWS-managed IAM policy, e.g. "AmazonBedrockFullAccess".'
    return f'arn:{auth.partition}:iam::aws:policy/{name}'

# %% ../nbs/00_core.ipynb #2e66f433
def tag_list(tags, key='Key', value='Value') -> list:
    'dict -> AWS tag list. Pass key/value for APIs that use TagKey/TagValue or key/value.'
    return [{key: k, value: str(v)} for k, v in (tags or {}).items()]

def tag_dict(items, key='Key', value='Value') -> dict:
    'AWS tag list -> dict. Inverse of `tag_list`.'
    return {i[key]: i[value] for i in (items or [])}

def named(name, tags=None) -> dict:
    'Tag dict with a Name tag merged in; explicit tags win.'
    return {'Name': name, **(tags or {})}

# %% ../nbs/00_core.ipynb #88ff331e
def create_kms_key(auth, alias, description=None, rotation=True, tags=None) -> dict:
    'Create or fetch a customer-managed KMS key by alias, with annual rotation enabled.'
    kms = auth.client('kms')
    alias = alias if alias.startswith('alias/') else f'alias/{alias}'
    try: return kms.describe_key(KeyId=alias)['KeyMetadata']
    except kms.exceptions.NotFoundException: pass
    key = kms.create_key(Description=description or alias, KeyUsage='ENCRYPT_DECRYPT',
                         Tags=tag_list(tags, 'TagKey', 'TagValue'))['KeyMetadata']
    kms.create_alias(AliasName=alias, TargetKeyId=key['KeyId'])
    if rotation: kms.enable_key_rotation(KeyId=key['KeyId'])
    return key

def kms_key_arn(auth, alias) -> str:
    'ARN of a KMS key looked up by alias.'
    alias = alias if alias.startswith('alias/') else f'alias/{alias}'
    return auth.client('kms').describe_key(KeyId=alias)['KeyMetadata']['Arn']

def _cmk(auth, name, compliance) -> str:
    'Key ARN for a stack when the profile demands a CMK, else None (falls back to AWS-owned keys).'
    return kms_key_arn(auth, f'{name}-key') if compliance.get('cmk') else None

# %% ../nbs/00_core.ipynb #9bd6fd06
def wait_for(client, waiter, delay=15, attempts=120, **kw):
    'Block on a boto3 waiter, with a ceiling generous enough for EKS and RDS (default 30 minutes).'
    client.get_waiter(waiter).wait(WaiterConfig={'Delay': delay, 'MaxAttempts': attempts}, **kw)

def poll_until(fn, ready, delay=15, timeout=1800, desc='resource'):
    'Poll fn() until ready(result). For services boto3 gives no waiter for. Returns the last result.'
    deadline = time.monotonic() + timeout
    while True:
        r = fn()
        if ready(r): return r
        if time.monotonic() >= deadline:
            raise TimeoutError(f'{desc} was still not ready after {timeout}s')
        time.sleep(delay)

# %% ../nbs/00_core.ipynb #6e96e033
def resource_group(auth, name, tags=None) -> dict:
    'Create or update a tag-query Resource Group. Defaults to querying tag ResourceGroup=<name>.'
    tags = tags or {'ResourceGroup': name}
    query = json.dumps({'ResourceTypeFilters': ['AWS::AllSupported'],
                        'TagFilters': [{'Key': k, 'Values': [str(v)]} for k, v in tags.items()]})
    rq = {'Type': 'TAG_FILTERS_1_0', 'Query': query}
    c = auth.client('resource-groups')
    found = first(g for g in list_resource_groups(auth) if g['GroupName'] == name)
    if found is None:
        g = c.create_group(Name=name, ResourceQuery=rq,
                           Tags={**tags, 'ResourceGroup': name})['Group']
        return {'Name': g['Name'], 'GroupArn': g['GroupArn']}
    # The saved query has its own call — update_group only edits the description.
    c.update_group_query(Group=name, ResourceQuery=rq)
    return {'Name': found['GroupName'], 'GroupArn': found['GroupArn']}

def resource_group_query(auth, name) -> dict:
    'The saved tag query behind a resource group.'
    q = auth.client('resource-groups').get_group_query(Group=name)['GroupQuery']
    return json.loads(q['ResourceQuery']['Query'])

def list_resource_groups(auth) -> list:
    'All resource groups in the account/region.'
    p = auth.client('resource-groups').get_paginator('list_groups')
    return [g for pg in p.paginate() for g in pg['GroupIdentifiers']]

def delete_resource_group(auth, name):
    'Delete a resource group. The resources it selected are left untouched.'
    auth.client('resource-groups').delete_group(Group=name)

# %% ../nbs/00_core.ipynb #d3f4f94f
class GenAIStack:
    'Provision a compliance-hardened enterprise GenAI stack on AWS in one call.'
    def __init__(self, auth, name, compliance=None):
        self.auth, self.name = auth, name
        self.compliance = Compliance(**(compliance if compliance is not None else ISO27001))
        self.resources = {}

    @property
    def bucket(self) -> str:
        'Document bucket name — account id included because S3 names are globally unique.'
        return f'{self.name}-{self.auth.account_id}-data'

    @property
    def ledger(self):
        'Tag-based inventory of everything this stack provisioned: `.audit()`, `.destroy()`.'
        from awseasy.ledger import Ledger
        return Ledger(self.auth, self.name)

    def provision(self, s3=True, knowledge_base=True, guardrail=True, dynamodb=True,
                  redis=False, sso=False, cdn=False, callback_urls=None, domains=None,
                  wait=False) -> dict:
        'Create every enabled resource. Safe to re-run: each step is create-or-update.'
        from awseasy.ai import create_guardrail, create_kb, create_aoss_collection, bedrock_policy
        from awseasy.auth import create_app_client, create_pool_domain, create_user_pool
        from awseasy.cdn import create_distribution, create_waf
        from awseasy.data import create_bucket, create_redis, create_table
        from awseasy.ledger import ledger_tags
        from awseasy.network import attach_policy, create_role, put_role_policy

        auth, name, r = self.auth, self.name, self.resources
        # Every resource carries the stack tag, which is what makes `self.ledger` work.
        c = self.compliance | dict(tags=ledger_tags(name, self.compliance.get('tags')))
        if c.get('cmk'): r['kms'] = create_kms_key(auth, f'{name}-key', tags=c.get('tags'))
        key_arn = r['kms']['Arn'] if 'kms' in r else None

        # Bedrock service role, scoped to this stack's bucket and key rather than a wildcard.
        r['role'] = create_role(auth, f'{name}-role', service='bedrock.amazonaws.com',
                                source_account=auth.account_id, tags=c.get('tags'))
        if c.get('least_privilege'):
            put_role_policy(auth, f'{name}-role', f'{name}-bedrock',
                            bedrock_policy(auth, bucket=self.bucket if s3 else None, kms_key_arn=key_arn))
        else:
            attach_policy(auth, f'{name}-role', aws_policy(auth, 'AmazonBedrockFullAccess'))
        role = r['role']['Role']['Arn']

        if s3: r['s3'] = create_bucket(auth, self.bucket, kms_key_id=key_arn, **c)
        if guardrail: r['guardrail'] = create_guardrail(auth, f'{name}-guardrail', kms_key_arn=key_arn, **c)
        if knowledge_base and s3:
            r['vectors'] = create_aoss_collection(auth, f'{name}-vectors', role_arns=[role], **c)
            r['kb'] = create_kb(auth, f'{name}-kb', bucket=self.bucket, role_arn=role,
                                collection_arn=r['vectors']['arn'], **c)
        if dynamodb: r['dynamodb'] = create_table(auth, f'{name}-sessions', 'id', kms_key_id=key_arn, **c)
        if redis: r['redis'] = create_redis(auth, f'{name}-cache', kms_key_id=key_arn,
                                            wait=wait, **c)

        if sso:
            r['user_pool'] = create_user_pool(auth, f'{name}-users', **c)
            pool_id = r['user_pool']['Id']
            r['sso_domain'] = create_pool_domain(auth, pool_id, f'{name}-{auth.account_id}')
            r['app_client'] = create_app_client(auth, pool_id, f'{name}-web',
                                                callback_urls=callback_urls or [])
        if cdn:
            r['waf'] = create_waf(auth, f'{name}-waf', scope='CLOUDFRONT', tags=c.get('tags'))
            r['cdn'] = create_distribution(auth, name, s3_bucket=self.bucket if s3 else None,
                                           domains=domains, waf_acl_arn=r['waf']['ARN'],
                                           wait=wait, **c)
        return r

    def summary(self) -> dict:
        'Identifiers for everything provisioned. Never contains a secret value.'
        return {k: _resource_id(v) for k, v in self.resources.items()}

    def __repr__(self): return f'GenAIStack({self.name!r}, {len(self.resources)} resources)'

_ID_KEYS = ('knowledgeBaseId', 'guardrailId', 'collectionEndpoint', 'DomainName', 'BucketName',
            'ReplicationGroupId', 'TableName', 'DistributionArn', 'ARN', 'Arn', 'arn', 'Id', 'Name', 'name')

def _resource_id(v):
    'Best-effort single identifier for a resource dict, checking the most specific keys first.'
    if not isinstance(v, dict): return str(v)
    for k in _ID_KEYS:
        if k in v and isinstance(v[k], str): return v[k]
    for k in ('Role', 'Group', 'Secret', 'UserPool'):
        if k in v and isinstance(v[k], dict): return _resource_id(v[k])
    return str(v)

# %% ../nbs/00_core.ipynb #d35f6855
def repo_root(path=None) -> Path:
    'Nearest ancestor directory containing a .git, else the starting directory.'
    p = Path(path or '.').resolve()
    for d in [p, *p.parents]:
        if (d / '.git').exists(): return d
    return p

def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy the bundled SKILL.md to .agents/skills/awseasy/ and ~/.claude/skills/awseasy/.'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    src = base / 'SKILL.md'
    if not src.exists(): return print(f'no SKILL.md alongside {base}')
    targets = [repo_root(dir) / '.agents/skills/awseasy/SKILL.md',
               Path.home() / '.claude/skills/awseasy/SKILL.md']
    if dry_run: return print(f'Would copy to: {[str(p) for p in targets]}')
    for p in targets: p.mk_write(src.read_text(encoding='utf-8'))
    print(f'Installed -> {[str(p) for p in targets]}')
