"""S3, DynamoDB, RDS PostgreSQL, and ElastiCache Redis for GenAI data infrastructure."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['create_bucket', 'bucket_url', 'presigned_url', 'bucket_conn', 'create_table', 'table_resource', 'dynamo_conn',
           'create_postgres', 'postgres_conn', 'create_redis', 'redis_conn']

# %% ../nbs/02_data.ipynb #223ecd3a
import json as _json
import secrets as _secrets_mod

# %% ../nbs/02_data.ipynb #4c71fcee
def _s3(auth):
    return auth.session.client('s3')

def create_bucket(auth, name, versioning=True, tags=None, **compliance_opts) -> dict:
    'Create S3 bucket. Blocks public access, enables SSE-S3 encryption by default.'
    s3 = _s3(auth)
    kwargs = {'Bucket': name}
    if auth.region != 'us-east-1':
        kwargs['CreateBucketConfiguration'] = {'LocationConstraint': auth.region}
    try:
        s3.create_bucket(**kwargs)
    except s3.exceptions.BucketAlreadyOwnedByYou:
        pass
    # Block all public access
    s3.put_public_access_block(
        Bucket=name,
        PublicAccessBlockConfiguration={
            'BlockPublicAcls': True, 'IgnorePublicAcls': True,
            'BlockPublicPolicy': True, 'RestrictPublicBuckets': True,
        })
    # Encryption
    s3.put_bucket_encryption(
        Bucket=name,
        ServerSideEncryptionConfiguration={
            'Rules': [{'ApplyServerSideEncryptionByDefault':
                       {'SSEAlgorithm': 'AES256'}}]})
    if versioning:
        s3.put_bucket_versioning(
            Bucket=name, VersioningConfiguration={'Status': 'Enabled'})
    if tags:
        s3.put_bucket_tagging(
            Bucket=name,
            Tagging={'TagSet': [{'Key': k, 'Value': v} for k, v in tags.items()]})
    return {'BucketName': name, 'Region': auth.region}

def bucket_url(name, key) -> str:
    'Return the s3:// URI for a bucket/key.'
    return f's3://{name}/{key}'

def presigned_url(auth, name, key, hours=1) -> str:
    'Generate a presigned GET URL for a S3 object.'
    return _s3(auth).generate_presigned_url(
        'get_object', Params={'Bucket': name, 'Key': key},
        ExpiresIn=hours * 3600)

def bucket_conn(name) -> str:
    'Return the bucket name (use with boto3 resource/client directly).'
    return name

# %% ../nbs/02_data.ipynb #6076afc9
def _dynamo(auth):
    return auth.session.client('dynamodb')

def create_table(auth, name, partition_key, sort_key=None,
                 billing_mode='PAY_PER_REQUEST', tags=None, **compliance_opts) -> dict:
    'Create DynamoDB table with point-in-time recovery enabled.'
    client = _dynamo(auth)
    key_schema = [{'AttributeName': partition_key, 'KeyType': 'HASH'}]
    attr_defs = [{'AttributeName': partition_key, 'AttributeType': 'S'}]
    if sort_key:
        key_schema.append({'AttributeName': sort_key, 'KeyType': 'RANGE'})
        attr_defs.append({'AttributeName': sort_key, 'AttributeType': 'S'})
    tag_list = [{'Key': k, 'Value': v} for k, v in (tags or {}).items()]
    try:
        resp = client.create_table(
            TableName=name,
            KeySchema=key_schema,
            AttributeDefinitions=attr_defs,
            BillingMode=billing_mode,
            Tags=tag_list,
        )['TableDescription']
    except client.exceptions.ResourceInUseException:
        resp = client.describe_table(TableName=name)['Table']
    # Enable PITR
    client.update_continuous_backups(
        TableName=name,
        PointInTimeRecoverySpecification={'PointInTimeRecoveryEnabled': True})
    return resp

def table_resource(auth, name):
    'Return a boto3 DynamoDB Table resource for direct operations.'
    return auth.session.resource('dynamodb').Table(name)

def dynamo_conn(auth, name) -> str:
    'Return the table name (use with boto3 DynamoDB client/resource directly).'
    return name

# %% ../nbs/02_data.ipynb #e06b1fc0
def _rds(auth):
    return auth.session.client('rds')

def create_postgres(auth, name, instance_class='db.t3.medium', engine_version='16.3',
                    master_username='pgadmin', master_password=None,
                    multi_az=False, deletion_protection=False,
                    tags=None, **compliance_opts) -> dict:
    'Create RDS PostgreSQL instance with encryption-at-rest enabled. Password stored in Secrets Manager.'
    from .network import create_secret
    client = _rds(auth)
    tag_list = [{'Key': k, 'Value': v} for k, v in (tags or {}).items()]
    password = master_password or _secrets_mod.token_urlsafe(24)
    try:
        inst = client.create_db_instance(
            DBInstanceIdentifier=name,
            DBInstanceClass=instance_class,
            Engine='postgres',
            EngineVersion=engine_version,
            MasterUsername=master_username,
            MasterUserPassword=password,
            MultiAZ=multi_az,
            StorageEncrypted=True,
            DeletionProtection=deletion_protection,
            AllocatedStorage=20,
            BackupRetentionPeriod=compliance_opts.get('backup_retention', 7),
            Tags=tag_list,
        )['DBInstance']
        # Persist credentials so callers can retrieve them later
        create_secret(auth, f'rds/{name}/master',
                      _json.dumps({'username': master_username, 'password': password}))
        inst['MasterSecretArn'] = f'rds/{name}/master'
    except client.exceptions.DBInstanceAlreadyExistsFault:
        inst = client.describe_db_instances(
            DBInstanceIdentifier=name)['DBInstances'][0]
    return inst

def postgres_conn(auth, name, db='postgres') -> str:
    'Return a postgresql:// connection string (password not included — use Secrets Manager).'
    inst = _rds(auth).describe_db_instances(
        DBInstanceIdentifier=name)['DBInstances'][0]
    host = inst['Endpoint']['Address']
    port = inst['Endpoint']['Port']
    user = inst['MasterUsername']
    return f'postgresql://{user}@{host}:{port}/{db}'

# %% ../nbs/02_data.ipynb #449200e2
def _elasticache(auth):
    return auth.session.client('elasticache')

def create_redis(auth, name, node_type='cache.t3.micro', num_shards=1,
                 tags=None, **compliance_opts) -> dict:
    'Create ElastiCache Redis OSS cluster with in-transit encryption.'
    client = _elasticache(auth)
    tag_list = [{'Key': k, 'Value': v} for k, v in (tags or {}).items()]
    multi_az = compliance_opts.get('multi_az', False)
    try:
        return client.create_replication_group(
            ReplicationGroupId=name,
            ReplicationGroupDescription=name,
            CacheNodeType=node_type,
            Engine='redis',
            NumNodeGroups=num_shards,
            ReplicasPerNodeGroup=1 if multi_az else 0,
            TransitEncryptionEnabled=True,
            AtRestEncryptionEnabled=True,
            Tags=tag_list,
        )['ReplicationGroup']
    except client.exceptions.ReplicationGroupAlreadyExistsFault:
        return client.describe_replication_groups(
            ReplicationGroupId=name)['ReplicationGroups'][0]

def redis_conn(auth, name) -> str:
    'Return the redis:// connection string for the primary endpoint.'
    rg = _elasticache(auth).describe_replication_groups(
        ReplicationGroupId=name)['ReplicationGroups'][0]
    ep = rg['NodeGroups'][0]['PrimaryEndpoint']
    return f'rediss://{ep["Address"]}:{ep["Port"]}'
