"""S3 document buckets, DynamoDB session tables, RDS PostgreSQL, and ElastiCache Redis — encrypted and private by default.

Docs: https://vedicreader.github.io/awseasy/data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['tls_only_policy', 'create_bucket', 'bucket_url', 'presigned_url', 'create_table', 'table_resource', 'create_postgres',
           'postgres_conn', 'postgres_password', 'postgres_iam_token', 'create_redis', 'redis_auth_token', 'redis_conn']

# %% ../nbs/02_data.ipynb #9377ffec
import json, secrets
from .core import named, tag_list, wait_for
from .network import create_secret, get_secret

# %% ../nbs/02_data.ipynb #68c5107f
def tls_only_policy(auth, bucket, tls_min='1.2') -> dict:
    'Bucket policy denying any request not made over TLS at or above `tls_min`.'
    b = auth.arn_for('s3', bucket, region='', account=False)
    res = [b, f'{b}/*']
    return {'Version': '2012-10-17', 'Statement': [
        {'Sid': 'DenyInsecureTransport', 'Effect': 'Deny', 'Principal': '*', 'Action': 's3:*',
         'Resource': res, 'Condition': {'Bool': {'aws:SecureTransport': 'false'}}},
        {'Sid': 'DenyOutdatedTLS', 'Effect': 'Deny', 'Principal': '*', 'Action': 's3:*',
         'Resource': res, 'Condition': {'NumericLessThan': {'s3:TlsVersion': tls_min}}}]}

def create_bucket(auth, name, versioning=True, kms_key_id=None, tls_min='1.2', log_bucket=None,
                  tags=None, **compliance_opts) -> dict:
    'Create a private, encrypted, versioned S3 bucket. Re-applies every control on an existing bucket.'
    s3 = auth.client('s3')
    kw = {'Bucket': name}
    if auth.region != 'us-east-1': kw['CreateBucketConfiguration'] = {'LocationConstraint': auth.region}
    try: s3.create_bucket(**kw)
    except (s3.exceptions.BucketAlreadyOwnedByYou, s3.exceptions.BucketAlreadyExists): pass
    s3.put_public_access_block(Bucket=name, PublicAccessBlockConfiguration=dict(
        BlockPublicAcls=True, IgnorePublicAcls=True, BlockPublicPolicy=True, RestrictPublicBuckets=True))
    sse = ({'SSEAlgorithm': 'aws:kms', 'KMSMasterKeyID': kms_key_id} if kms_key_id
           else {'SSEAlgorithm': 'AES256'})
    s3.put_bucket_encryption(Bucket=name, ServerSideEncryptionConfiguration={
        'Rules': [{'ApplyServerSideEncryptionByDefault': sse, 'BucketKeyEnabled': bool(kms_key_id)}]})
    s3.put_bucket_versioning(Bucket=name, VersioningConfiguration={
        'Status': 'Enabled' if versioning else 'Suspended'})
    if tls_min: s3.put_bucket_policy(Bucket=name, Policy=json.dumps(tls_only_policy(auth, name, tls_min)))
    if log_bucket:
        s3.put_bucket_logging(Bucket=name, BucketLoggingStatus={'LoggingEnabled': {
            'TargetBucket': log_bucket, 'TargetPrefix': f'{name}/'}})
    if tags: s3.put_bucket_tagging(Bucket=name, Tagging={'TagSet': tag_list(tags)})
    return {'BucketName': name, 'Region': auth.region,
            'Arn': auth.arn_for('s3', name, region='', account=False)}

def bucket_url(name, key='') -> str:
    'The s3:// URI for a bucket or object.'
    return f's3://{name}/{key}'

def presigned_url(auth, name, key, hours=1, method='get_object') -> str:
    'Time-limited URL for one object. Use this instead of ever making a bucket public.'
    return auth.client('s3').generate_presigned_url(
        method, Params={'Bucket': name, 'Key': key}, ExpiresIn=int(hours * 3600))

# %% ../nbs/02_data.ipynb #880bc901
def create_table(auth, name, partition_key, sort_key=None, billing_mode='PAY_PER_REQUEST',
                 kms_key_id=None, ttl_attr=None, deletion_protection=False, tags=None,
                 **compliance_opts) -> dict:
    'Create a DynamoDB table with point-in-time recovery. Idempotent by name.'
    c = auth.client('dynamodb')
    keys = [{'AttributeName': partition_key, 'KeyType': 'HASH'}]
    attrs = [{'AttributeName': partition_key, 'AttributeType': 'S'}]
    if sort_key:
        keys.append({'AttributeName': sort_key, 'KeyType': 'RANGE'})
        attrs.append({'AttributeName': sort_key, 'AttributeType': 'S'})
    sse = ({'Enabled': True, 'SSEType': 'KMS', 'KMSMasterKeyId': kms_key_id} if kms_key_id
           else {'Enabled': False})   # Enabled=False still encrypts, using the AWS-owned key
    try:
        t = c.create_table(TableName=name, KeySchema=keys, AttributeDefinitions=attrs,
                           BillingMode=billing_mode, SSESpecification=sse,
                           DeletionProtectionEnabled=deletion_protection,
                           Tags=tag_list(tags))['TableDescription']
    except c.exceptions.ResourceInUseException:
        t = c.describe_table(TableName=name)['Table']
    c.update_continuous_backups(TableName=name,
                                PointInTimeRecoverySpecification={'PointInTimeRecoveryEnabled': True})
    if ttl_attr:
        c.update_time_to_live(TableName=name,
                              TimeToLiveSpecification={'Enabled': True, 'AttributeName': ttl_attr})
    return t

def table_resource(auth, name):
    'boto3 DynamoDB Table resource, for get_item/put_item/query against the provisioned table.'
    return auth.resource('dynamodb').Table(name)

# %% ../nbs/02_data.ipynb #8c9cc7da
def create_postgres(auth, name, instance_class='db.t3.medium', engine_version='16.4',
                    master_username='pgadmin', storage=20, kms_key_id=None, subnet_group=None,
                    sg_ids=None, multi_az=False, deletion_protection=False, backup_retention=7,
                    audit=False, wait=False, tags=None, **compliance_opts) -> dict:
    'Create an encrypted, private RDS PostgreSQL instance. RDS generates and holds the master password.'
    c = auth.client('rds')
    kw = dict(DBInstanceIdentifier=name, DBInstanceClass=instance_class, Engine='postgres',
              EngineVersion=engine_version, MasterUsername=master_username,
              ManageMasterUserPassword=True,          # password lives in Secrets Manager, never here
              AllocatedStorage=storage, StorageEncrypted=True, StorageType='gp3',
              PubliclyAccessible=False, EnableIAMDatabaseAuthentication=True,
              MultiAZ=multi_az, DeletionProtection=deletion_protection,
              BackupRetentionPeriod=backup_retention, CopyTagsToSnapshot=True,
              AutoMinorVersionUpgrade=True, Tags=tag_list(named(name, tags)))
    if kms_key_id: kw.update(KmsKeyId=kms_key_id, MasterUserSecretKmsKeyId=kms_key_id)
    if subnet_group: kw['DBSubnetGroupName'] = subnet_group
    if sg_ids: kw['VpcSecurityGroupIds'] = sg_ids
    if audit: kw['EnableCloudwatchLogsExports'] = ['postgresql', 'upgrade']
    try: db = c.create_db_instance(**kw)['DBInstance']
    except c.exceptions.DBInstanceAlreadyExistsFault:
        db = c.describe_db_instances(DBInstanceIdentifier=name)['DBInstances'][0]
    if wait:
        # A new instance takes several minutes; the default waiter gives up too early.
        wait_for(c, 'db_instance_available', DBInstanceIdentifier=name)
        db = c.describe_db_instances(DBInstanceIdentifier=name)['DBInstances'][0]
    return db

def postgres_conn(auth, name, db='postgres') -> str:
    'A postgresql:// URL with no password in it. Fetch the password separately, or use an IAM token.'
    i = auth.client('rds').describe_db_instances(DBInstanceIdentifier=name)['DBInstances'][0]
    e = i['Endpoint']
    return f"postgresql://{i['MasterUsername']}@{e['Address']}:{e['Port']}/{db}?sslmode=require"

def postgres_password(auth, name) -> str:
    'Read the RDS-managed master password out of Secrets Manager.'
    i = auth.client('rds').describe_db_instances(DBInstanceIdentifier=name)['DBInstances'][0]
    arn = i.get('MasterUserSecret', {}).get('SecretArn')
    if not arn: raise ValueError(f'{name} has no RDS-managed master secret')
    v = auth.client('secretsmanager').get_secret_value(SecretId=arn)['SecretString']
    return json.loads(v)['password']

def postgres_iam_token(auth, name, user, db='postgres') -> str:
    'A 15-minute IAM auth token to use as the password — no stored credential at all.'
    i = auth.client('rds').describe_db_instances(DBInstanceIdentifier=name)['DBInstances'][0]
    return auth.client('rds').generate_db_auth_token(
        DBHostname=i['Endpoint']['Address'], Port=i['Endpoint']['Port'], DBUsername=user)

# %% ../nbs/02_data.ipynb #74b78ec3
def create_redis(auth, name, node_type='cache.t4g.micro', num_shards=1, replicas=0,
                 engine_version='7.1', kms_key_id=None, subnet_group=None, sg_ids=None,
                 multi_az=False, backup_retention=0, wait=False, tags=None,
                 **compliance_opts) -> dict:
    'Create an encrypted ElastiCache Redis replication group; the AUTH token goes to Secrets Manager.'
    c = auth.client('elasticache')
    if multi_az: replicas = max(replicas, 1)      # automatic failover needs at least one replica
    token = secrets.token_urlsafe(32)
    kw = dict(ReplicationGroupId=name, ReplicationGroupDescription=name, CacheNodeType=node_type,
              Engine='redis', EngineVersion=engine_version, NumNodeGroups=num_shards,
              ReplicasPerNodeGroup=replicas, TransitEncryptionEnabled=True,
              AtRestEncryptionEnabled=True, AuthToken=token,
              AutomaticFailoverEnabled=bool(replicas), MultiAZEnabled=multi_az,
              SnapshotRetentionLimit=backup_retention, Tags=tag_list(named(name, tags)))
    if kms_key_id: kw['KmsKeyId'] = kms_key_id
    if subnet_group: kw['CacheSubnetGroupName'] = subnet_group
    if sg_ids: kw['SecurityGroupIds'] = sg_ids
    try:
        rg = c.create_replication_group(**kw)['ReplicationGroup']
        create_secret(auth, f'elasticache/{name}/auth-token', token, kms_key_id=kms_key_id,
                      description=f'ElastiCache AUTH token for {name}')
    except c.exceptions.ReplicationGroupAlreadyExistsFault:
        rg = c.describe_replication_groups(ReplicationGroupId=name)['ReplicationGroups'][0]
    if wait:
        wait_for(c, 'replication_group_available', ReplicationGroupId=name)
        rg = c.describe_replication_groups(ReplicationGroupId=name)['ReplicationGroups'][0]
    return rg

def redis_auth_token(auth, name) -> str:
    'The AUTH token for a cluster created by `create_redis`.'
    return get_secret(auth, f'elasticache/{name}/auth-token')

def redis_conn(auth, name) -> str:
    'A rediss:// URL for the primary endpoint. TLS-only; there is no plaintext variant.'
    rg = auth.client('elasticache').describe_replication_groups(
        ReplicationGroupId=name)['ReplicationGroups'][0]
    ng = rg['NodeGroups'][0]
    ep = ng.get('PrimaryEndpoint') or ng['NodeGroupMembers'][0]['ReadEndpoint']
    return f"rediss://{ep['Address']}:{ep['Port']}"
