"""Getting a container image into ECR, either from a local Docker daemon or entirely inside AWS.

Docs: https://vedicreader.github.io/awseasy/images.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_images.ipynb.

# %% auto #0
__all__ = ['BUILD_IMAGE', 'ecr_credentials', 'ecr_login', 'default_tag', 'build_push', 'image_digest', 'scan_findings',
           'buildspec', 'ecr_push_policy', 'codebuild_role', 'create_image_project', 'project_drifted',
           'build_image_in_codebuild', 'build_status', 'upload_source']

# %% ../nbs/07_images.ipynb #4f883e24
import base64, json, os, subprocess, tempfile, time
from pathlib import Path
from fastcore.all import L, first
from .core import aws_policy, named, tag_list
from .compute import create_ecr, ecr_uri
from .network import attach_policy, create_role, put_role_policy

# %% ../nbs/07_images.ipynb #31e3e5d6
def ecr_credentials(auth) -> dict:
    'Short-lived ECR credentials as {username, password, registry}. Valid for 12 hours.'
    d = auth.client('ecr').get_authorization_token()['authorizationData'][0]
    user, _, password = base64.b64decode(d['authorizationToken']).decode().partition(':')
    return {'username': user, 'password': password, 'registry': d['proxyEndpoint']}

def ecr_login(auth, docker='docker') -> str:
    'Log the local Docker daemon into ECR. The token is piped over stdin, never passed as an argument.'
    c = ecr_credentials(auth)
    r = subprocess.run([docker, 'login', '--username', c['username'], '--password-stdin',
                        c['registry']], input=c['password'], text=True, capture_output=True)
    if r.returncode: raise RuntimeError(f"docker login failed: {r.stderr.strip()}")
    return c['registry']

# %% ../nbs/07_images.ipynb #e9a4260a
def default_tag() -> str:
    'A sortable, unique tag. Immutable repositories cannot take "latest" twice.'
    return time.strftime('%Y%m%d-%H%M%S', time.gmtime())

def build_push(auth, repo, path='.', tag=None, dockerfile=None, push=True, docker='docker') -> str:
    '''Build a container image locally and push it to ECR. Returns the full image URI.

    `dockerfile` is a `dockeasy.Dockerfile`; omit it to let `dockeasy.detect_app` infer one from
    the project at `path`. Requires a running Docker daemon — use `build_in_codebuild` if there
    is not one.'''
    from dockeasy import detect_app
    tag = tag or default_tag()
    uri = ecr_uri(auth, repo, tag)
    df = dockerfile if dockerfile is not None else detect_app(path)
    df.build(tag=uri, path=path)
    if push:
        ecr_login(auth, docker=docker)
        r = subprocess.run([docker, 'push', uri], capture_output=True, text=True)
        if r.returncode: raise RuntimeError(f'docker push failed: {r.stderr.strip()}')
    return uri

def image_digest(auth, repo, tag) -> str:
    'Immutable digest of a tag. Deploy by digest when you need to pin exactly what runs.'
    imgs = auth.client('ecr').describe_images(repositoryName=repo,
                                              imageIds=[{'imageTag': tag}])['imageDetails']
    return imgs[0]['imageDigest']

def scan_findings(auth, repo, tag) -> dict:
    'Vulnerability counts from the scan-on-push result, e.g. {"HIGH": 2, "MEDIUM": 5}.'
    r = auth.client('ecr').describe_image_scan_findings(repositoryName=repo,
                                                        imageId={'imageTag': tag})
    return r.get('imageScanFindings', {}).get('findingSeverityCounts', {})

# %% ../nbs/07_images.ipynb #f928c4b1
BUILD_IMAGE = 'aws/codebuild/standard:7.0'

def buildspec(auth, repo, dockerfile='Dockerfile', context='.') -> str:
    'Buildspec that logs into ECR, builds, and pushes $IMAGE_TAG. Returns YAML.'
    registry = f'{auth.account_id}.dkr.ecr.{auth.region}.amazonaws.com'
    return '\n'.join([
        'version: 0.2',
        'phases:',
        '  pre_build:',
        '    commands:',
        f'      - aws ecr get-login-password --region {auth.region} | '
        f'docker login --username AWS --password-stdin {registry}',
        '  build:',
        '    commands:',
        f'      - docker build -f {dockerfile} -t $IMAGE_URI:$IMAGE_TAG {context}',
        '  post_build:',
        '    commands:',
        '      - docker push $IMAGE_URI:$IMAGE_TAG',
        '      - |',
        '        aws ecr describe-images --repository-name $REPO_NAME '
        '--image-ids imageTag=$IMAGE_TAG --query "imageDetails[0].imageDigest" --output text',
    ]) + '\n'

def ecr_push_policy(auth, repo) -> dict:
    'Least-privilege policy for a build: push to one repository, and write its own logs.'
    return {'Version': '2012-10-17', 'Statement': [
        {'Sid': 'EcrAuth', 'Effect': 'Allow', 'Action': 'ecr:GetAuthorizationToken',
         'Resource': '*'},   # this action does not accept a resource; the push rights below do
        {'Sid': 'PushToOneRepo', 'Effect': 'Allow',
         'Action': ['ecr:BatchCheckLayerAvailability', 'ecr:CompleteLayerUpload',
                    'ecr:InitiateLayerUpload', 'ecr:PutImage', 'ecr:UploadLayerPart',
                    'ecr:BatchGetImage', 'ecr:DescribeImages'],
         'Resource': auth.arn_for('ecr', f'repository/{repo}')},
        {'Sid': 'WriteBuildLogs', 'Effect': 'Allow',
         'Action': ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
         'Resource': auth.arn_for('logs', 'log-group:/aws/codebuild/*')}]}

def codebuild_role(auth, name, repo, source_bucket=None) -> dict:
    'Service role for a CodeBuild image build, scoped to one ECR repository.'
    role = create_role(auth, name, service='codebuild.amazonaws.com',
                       source_account=auth.account_id)
    put_role_policy(auth, name, 'ecr-push', ecr_push_policy(auth, repo))
    if source_bucket:
        put_role_policy(auth, name, 'read-source', {
            'Version': '2012-10-17',
            'Statement': [{'Effect': 'Allow', 'Action': ['s3:GetObject', 's3:GetObjectVersion'],
                           'Resource': auth.arn_for('s3', f'{source_bucket}/*', region='',
                                                    account=False)}]})
    return role

def create_image_project(auth, name, repo, source_bucket=None, source_key=None, github_url=None,
                         dockerfile='Dockerfile', context='.', compute='BUILD_GENERAL1_SMALL',
                         build_image=BUILD_IMAGE, tags=None, **compliance_opts) -> dict:
    'Create a CodeBuild project that builds a container image and pushes it to ECR.'
    if bool(source_bucket) == bool(github_url):
        raise ValueError('pass exactly one of source_bucket= (with source_key=) or github_url=')
    create_ecr(auth, repo, **compliance_opts)
    role = codebuild_role(auth, f'{name}-build-role', repo, source_bucket)
    source = ({'type': 'S3', 'location': f'{source_bucket}/{source_key}'} if source_bucket
              else {'type': 'GITHUB', 'location': github_url})
    source['buildspec'] = buildspec(auth, repo, dockerfile, context)
    c = auth.client('codebuild')
    kw = dict(
        name=name, source=source, artifacts={'type': 'NO_ARTIFACTS'},
        serviceRole=role['Role']['Arn'],
        environment={'type': 'LINUX_CONTAINER', 'image': build_image, 'computeType': compute,
                     # docker build needs a Docker daemon inside the build container
                     'privilegedMode': True,
                     'environmentVariables': [
                         {'name': 'IMAGE_URI', 'value': ecr_uri(auth, repo)},
                         {'name': 'REPO_NAME', 'value': repo},
                         {'name': 'IMAGE_TAG', 'value': 'latest'}]})
    if tags: kw['tags'] = tag_list(tags, 'key', 'value')
    try: return c.create_project(**kw)['project']
    except c.exceptions.ResourceAlreadyExistsException:
        cur = c.batch_get_projects(names=[name])['projects'][0]
        if not project_drifted(cur, kw): return cur
        c.update_project(**kw)
        return c.batch_get_projects(names=[name])['projects'][0]

def project_drifted(current, wanted) -> bool:
    'True when a stored CodeBuild project differs from the config we would send.'
    src, env = current.get('source', {}), current.get('environment', {})
    w_src, w_env = wanted['source'], wanted['environment']
    return (src.get('buildspec') != w_src.get('buildspec')
            or src.get('location') != w_src.get('location')
            or src.get('type') != w_src.get('type')
            or env.get('image') != w_env['image']
            or env.get('computeType') != w_env['computeType']
            or env.get('privilegedMode') != w_env['privilegedMode']
            or current.get('serviceRole') != wanted['serviceRole'])

def build_image_in_codebuild(auth, project, tag=None) -> dict:
    'Start a build. Returns the build record; poll it with `build_status`.'
    tag = tag or default_tag()
    return auth.client('codebuild').start_build(
        projectName=project,
        environmentVariablesOverride=[{'name': 'IMAGE_TAG', 'value': tag,
                                       'type': 'PLAINTEXT'}])['build']

def build_status(auth, build_id) -> str:
    'IN_PROGRESS, SUCCEEDED, FAILED, ...'
    return auth.client('codebuild').batch_get_builds(ids=[build_id])['builds'][0]['buildStatus']

def upload_source(auth, bucket, key, path='.') -> str:
    'Zip a directory and upload it as CodeBuild S3 source. Returns "bucket/key".'
    import zipfile
    root = Path(path).resolve()
    skip = {'.git', '__pycache__', '.venv', 'node_modules', '.ipynb_checkpoints'}
    with tempfile.NamedTemporaryFile(suffix='.zip', delete=False) as f: tmp = f.name
    try:
        with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as z:
            for p in root.rglob('*'):
                if p.is_file() and not skip & set(p.relative_to(root).parts):
                    z.write(p, p.relative_to(root))
        auth.client('s3').upload_file(tmp, bucket, key)
    finally: Path(tmp).unlink(missing_ok=True)
    return f'{bucket}/{key}'
