"""Tag-based inventory, security audit, and teardown for everything a stack created — with no state file.

Docs: https://vedicreader.github.io/awseasy/ledger.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_ledger.ipynb.

# %% auto #0
__all__ = ['LEDGER_TAG', 'AUDITORS', 'DELETERS', 'ledger_tags', 'parse_arn', 'Ledger', 'auditor', 'finding', 'audit_resource',
           'deleter', 'destroy_resources']

# %% ../nbs/08_ledger.ipynb #458d28e8
import json
from fastcore.all import L, first
from .core import tag_dict, tag_list

# %% ../nbs/08_ledger.ipynb #5e9a62dc
LEDGER_TAG = 'awseasy:stack'

def ledger_tags(stack, tags=None) -> dict:
    'Tag dict marking a resource as part of `stack`. The stack tag always wins.'
    return {**(tags or {}), LEDGER_TAG: stack}

def parse_arn(arn) -> dict:
    '''Split an ARN into partition/service/region/account/type/name.

    The tail takes three shapes — `type/name` (dynamodb, ec2), `type:name` (rds, secretsmanager),
    and a bare `name` (s3) — so the *first* separator wins. Checking one before the other splits
    a Secrets Manager ARN like `secret:app/key-AbCdEf` in the wrong place.'''
    p = arn.split(':', 5)
    tail = p[5] if len(p) > 5 else ''
    seps = [i for i in (tail.find(':'), tail.find('/')) if i >= 0]
    if seps: i = min(seps); rtype, name = tail[:i], tail[i + 1:]
    else:    rtype, name = '', tail
    return dict(arn=arn, partition=p[1], service=p[2], region=p[3], account=p[4],
                type=rtype, name=name)

# %% ../nbs/08_ledger.ipynb #bc439876
class Ledger:
    '''Tag-based inventory of a stack. AWS is the state store; there is no state file.

    Backed by the Resource Groups Tagging API, so it sees resources created by anything that
    applied the tag — this library, the console, Terraform, or a colleague's script.'''
    def __init__(self, auth, stack):
        self.auth, self.stack = auth, stack

    def _client(self): return self.auth.client('resourcegroupstaggingapi')

    def resources(self, services=None) -> list:
        'Every tagged resource in the stack, as [{arn, service, type, name, tags}].'
        p = self._client().get_paginator('get_resources')
        out = []
        for page in p.paginate(TagFilters=[{'Key': LEDGER_TAG, 'Values': [self.stack]}]):
            for m in page['ResourceTagMappingList']:
                r = parse_arn(m['ResourceARN'])
                r['tags'] = tag_dict(m.get('Tags', []))
                out.append(r)
        if services: out = [r for r in out if r['service'] in set(services)]
        return sorted(out, key=lambda r: (r['service'], r['type'], r['name']))

    def arns(self) -> list: return [r['arn'] for r in self.resources()]

    def by_service(self) -> dict:
        'Resource ARNs grouped by service, for a quick read of what a stack consists of.'
        out = {}
        for r in self.resources(): out.setdefault(r['service'], []).append(r['arn'])
        return out

    def adopt(self, arns, tags=None) -> dict:
        'Tag existing resources into the stack so inventory, audit, and destroy cover them too.'
        r = self._client().tag_resources(ResourceARNList=list(arns),
                                         Tags=ledger_tags(self.stack, tags))
        return r.get('FailedResourcesMap', {})

    def release(self, arns) -> dict:
        'Remove the stack tag, so destroy() will no longer touch these resources.'
        r = self._client().untag_resources(ResourceARNList=list(arns), TagKeys=[LEDGER_TAG])
        return r.get('FailedResourcesMap', {})

    def audit(self, failures_only=True) -> list:
        'Check the security controls this library claims to enforce. See `audit_resource`.'
        out = [f for r in self.resources() for f in audit_resource(self.auth, r)]
        return [f for f in out if not f['ok']] if failures_only else out

    def destroy(self, dry_run=True, services=None) -> dict:
        'Delete the stack, dependents first. dry_run=True by default — this is irreversible.'
        return destroy_resources(self.auth, self.resources(services), dry_run=dry_run)

    def __repr__(self):
        return f'Ledger({self.stack!r}, {len(self.arns())} resources)'

# %% ../nbs/08_ledger.ipynb #e5639f2f
AUDITORS = {}

def auditor(service, type=''):
    'Register a check for one resource type. Auditors take (auth, resource) and yield findings.'
    def deco(fn): AUDITORS[(service, type)] = fn; return fn
    return deco

def finding(r, check, ok, detail='') -> dict:
    return {'arn': r['arn'], 'name': r['name'], 'check': check, 'ok': bool(ok), 'detail': detail}

def audit_resource(auth, r) -> list:
    'Run the registered auditor for a resource. Unknown types report as unchecked, never as passing.'
    fn = AUDITORS.get((r['service'], r['type']))
    if fn is None: return [finding(r, f"{r['service']}:unchecked", True, 'no auditor registered')]
    try: return list(fn(auth, r))
    except Exception as e: return [finding(r, f"{r['service']}:error", False, str(e)[:200])]

@auditor('s3')
def _audit_s3(auth, r):
    s3, b = auth.client('s3'), r['name']
    try: pab = s3.get_public_access_block(Bucket=b)['PublicAccessBlockConfiguration']
    except s3.exceptions.ClientError: pab = {}
    yield finding(r, 's3:public-access-block', pab and all(pab.values()),
                  f'set: {sorted(k for k, v in pab.items() if v)}')
    try:
        rules = s3.get_bucket_encryption(Bucket=b)['ServerSideEncryptionConfiguration']['Rules']
        alg = rules[0]['ApplyServerSideEncryptionByDefault']['SSEAlgorithm']
    except s3.exceptions.ClientError: alg = None
    yield finding(r, 's3:encryption', alg is not None, f'algorithm: {alg}')
    try: pol = json.loads(s3.get_bucket_policy(Bucket=b)['Policy'])['Statement']
    except s3.exceptions.ClientError: pol = []
    tls = any(s.get('Effect') == 'Deny'
              and s.get('Condition', {}).get('Bool', {}).get('aws:SecureTransport') == 'false'
              for s in pol)
    yield finding(r, 's3:tls-only', tls, 'bucket policy denies aws:SecureTransport=false')
    ver = s3.get_bucket_versioning(Bucket=b).get('Status')
    yield finding(r, 's3:versioning', ver == 'Enabled', f'status: {ver}')

@auditor('dynamodb', 'table')
def _audit_dynamodb(auth, r):
    c = auth.client('dynamodb')
    cb = c.describe_continuous_backups(TableName=r['name'])['ContinuousBackupsDescription']
    st = cb['PointInTimeRecoveryDescription']['PointInTimeRecoveryStatus']
    yield finding(r, 'dynamodb:pitr', st == 'ENABLED', f'status: {st}')

@auditor('rds', 'db')
def _audit_rds(auth, r):
    d = auth.client('rds').describe_db_instances(DBInstanceIdentifier=r['name'])['DBInstances'][0]
    yield finding(r, 'rds:not-public', not d.get('PubliclyAccessible'), '')
    yield finding(r, 'rds:encrypted', d.get('StorageEncrypted'), '')
    yield finding(r, 'rds:iam-auth', d.get('IAMDatabaseAuthenticationEnabled'), '')
    yield finding(r, 'rds:backups', d.get('BackupRetentionPeriod', 0) > 0,
                  f"retention: {d.get('BackupRetentionPeriod')} days")

@auditor('kms', 'key')
def _audit_kms(auth, r):
    c = auth.client('kms')
    rot = c.get_key_rotation_status(KeyId=r['name']).get('KeyRotationEnabled')
    yield finding(r, 'kms:rotation', rot, '')

@auditor('ec2', 'instance')
def _audit_ec2(auth, r):
    c = auth.client('ec2')
    i = c.describe_instances(InstanceIds=[r['name']])['Reservations'][0]['Instances'][0]
    yield finding(r, 'ec2:imdsv2', i.get('MetadataOptions', {}).get('HttpTokens') == 'required', '')
    vols = [b['Ebs']['VolumeId'] for b in i.get('BlockDeviceMappings', []) if 'Ebs' in b]
    enc = [v['Encrypted'] for v in c.describe_volumes(VolumeIds=vols)['Volumes']] if vols else []
    yield finding(r, 'ec2:ebs-encrypted', enc and all(enc), f'{sum(enc)}/{len(enc)} volumes')

@auditor('elasticache', 'replicationgroup')
def _audit_elasticache(auth, r):
    g = auth.client('elasticache').describe_replication_groups(
        ReplicationGroupId=r['name'])['ReplicationGroups'][0]
    yield finding(r, 'elasticache:transit-encryption', g.get('TransitEncryptionEnabled'), '')
    yield finding(r, 'elasticache:at-rest-encryption', g.get('AtRestEncryptionEnabled'), '')

@auditor('ecr', 'repository')
def _audit_ecr(auth, r):
    repo = auth.client('ecr').describe_repositories(
        repositoryNames=[r['name']])['repositories'][0]
    yield finding(r, 'ecr:immutable-tags', repo.get('imageTagMutability') == 'IMMUTABLE', '')
    yield finding(r, 'ecr:scan-on-push',
                  repo.get('imageScanningConfiguration', {}).get('scanOnPush'), '')

# %% ../nbs/08_ledger.ipynb #29af405d
DELETERS = {}

def deleter(service, type='', order=50):
    'Register a deleter. Lower `order` runs first, so dependents go before their dependencies.'
    def deco(fn): DELETERS[(service, type)] = (order, fn); return fn
    return deco

def destroy_resources(auth, resources, dry_run=True) -> dict:
    'Delete resources dependents-first. Returns {plan, deleted, unsupported, failed}.'
    known = [r for r in resources if (r['service'], r['type']) in DELETERS]
    unknown = [r for r in resources if (r['service'], r['type']) not in DELETERS]
    known.sort(key=lambda r: DELETERS[(r['service'], r['type'])][0])
    out = {'plan': [r['arn'] for r in known], 'deleted': [], 'failed': [],
           'unsupported': [{'arn': r['arn'],
                            'reason': f"no deleter for {r['service']}:{r['type'] or '-'}"}
                           for r in unknown]}
    if dry_run: return out
    for r in known:
        try:
            DELETERS[(r['service'], r['type'])][1](auth, r)
            out['deleted'].append(r['arn'])
        except Exception as e:
            out['failed'].append({'arn': r['arn'], 'error': f'{type(e).__name__}: {str(e)[:200]}'})
    return out

# Compute and edge first, then data stores, then the network and keys they depend on.
@deleter('ec2', 'instance', order=10)
def _rm_instance(auth, r): auth.client('ec2').terminate_instances(InstanceIds=[r['name']])

@deleter('elasticache', 'replicationgroup', order=20)
def _rm_redis(auth, r):
    auth.client('elasticache').delete_replication_group(ReplicationGroupId=r['name'],
                                                        RetainPrimaryCluster=False)

@deleter('rds', 'db', order=20)
def _rm_rds(auth, r):
    c = auth.client('rds')
    c.modify_db_instance(DBInstanceIdentifier=r['name'], DeletionProtection=False,
                         ApplyImmediately=True)
    c.delete_db_instance(DBInstanceIdentifier=r['name'], SkipFinalSnapshot=True,
                         DeleteAutomatedBackups=True)

@deleter('es', 'domain', order=20)
def _rm_opensearch(auth, r): auth.client('opensearch').delete_domain(DomainName=r['name'])

@deleter('dynamodb', 'table', order=30)
def _rm_table(auth, r):
    c = auth.client('dynamodb')
    c.update_table(TableName=r['name'], DeletionProtectionEnabled=False)
    c.delete_table(TableName=r['name'])

@deleter('ecr', 'repository', order=30)
def _rm_ecr(auth, r): auth.client('ecr').delete_repository(repositoryName=r['name'], force=True)

@deleter('cognito-idp', 'userpool', order=30)
def _rm_pool(auth, r):
    c = auth.client('cognito-idp')
    c.update_user_pool(UserPoolId=r['name'], DeletionProtection='INACTIVE')
    c.delete_user_pool(UserPoolId=r['name'])

@deleter('s3', order=40)
def _rm_bucket(auth, r):
    'S3 refuses to delete a non-empty bucket, so every version and delete marker goes first.'
    s3 = auth.client('s3')
    p = s3.get_paginator('list_object_versions')
    for page in p.paginate(Bucket=r['name']):
        objs = [{'Key': o['Key'], 'VersionId': o['VersionId']}
                for k in ('Versions', 'DeleteMarkers') for o in page.get(k, [])]
        if objs: s3.delete_objects(Bucket=r['name'], Delete={'Objects': objs})
    s3.delete_bucket(Bucket=r['name'])

@deleter('secretsmanager', 'secret', order=50)
def _rm_secret(auth, r):
    auth.client('secretsmanager').delete_secret(SecretId=r['arn'],
                                                ForceDeleteWithoutRecovery=True)

@deleter('ec2', 'vpc-endpoint', order=60)
def _rm_endpoint(auth, r): auth.client('ec2').delete_vpc_endpoints(VpcEndpointIds=[r['name']])

@deleter('ec2', 'security-group', order=70)
def _rm_sg(auth, r): auth.client('ec2').delete_security_group(GroupId=r['name'])

@deleter('ec2', 'subnet', order=80)
def _rm_subnet(auth, r): auth.client('ec2').delete_subnet(SubnetId=r['name'])

@deleter('ec2', 'vpc', order=90)
def _rm_vpc(auth, r): auth.client('ec2').delete_vpc(VpcId=r['name'])

@deleter('kms', 'key', order=100)
def _rm_key(auth, r):
    'Scheduled, not deleted: AWS enforces a waiting period, and data encrypted with it stays readable.'
    auth.client('kms').schedule_key_deletion(KeyId=r['name'], PendingWindowInDays=7)
